.travis.yml
https://travis-ci.org/ is a continuous integration system that is free for open-source projects hosted on github.
Administrators of the repository can set it up so that it makes sure the code compiles after each new commit.
It is also possible to make pull requests dependent on not breaking the build using github status checks.
In addition to a simple build test, it would also be possible to clone the testsuite repo and make sure that all the tests pass at each commit as well.
=> Add initial file for travis

symtabAPI/src/Object.h
Fixed forgotten rename of isPPC64V2API to getABIVersion in
Object.h.  The virtual function in this base class now returns
false indicating that it is not implemented (which is the case
for Object-nt).
=> Provided base class virtual for getABIVersion() that returns false when not implemented

common/src/linuxKludges.C
The error cases all return false anyway, so the caller can deal with
failure, which makes this stderr chatter just spam.
Fixes #36.
=> Remove low-level warnings from ptrace read/write failures

symtabAPI/src/Module.C, symtabAPI/src/Object-elf.C
These cout writes were added by commit 758aa22669b4a, but we don't want
such output in general use.
=> symtabAPI: comment out some debug chatter

symtabAPI/src/Object-elf.C
The cuDIE in parseLineInfoForCU is a parameter, so it shouldn't act like
it owns this.  But it was calling dwarf_dealloc when that CU had no line
info, which led to a double-free crash when the callers tried to free
that cuDIE itself.  Just return and let the proper owner do it.
The double-free was easily reproducible on Fedora 23 x86_64, test1_30.
=> symtabAPI: don't free cuDIE in parseLineInfoForCU

dyninstAPI/src/addressSpace.C, dyninstAPI/src/binaryEdit.C, symtabAPI/src/emitElf-64.C
Valgrind complained of uninitialized data in pwrite during elf_update.
Using --track-origins=yes found three origins to fix:
- trap_mapping_header has a padding field that was unset.  Use memset on
the whole thing to be sure it's fully initialized.
- Parts of .dyninstInst may not be written due to gaps from inferior
realloc or free.  Use calloc to initially zero this buffer.
- The new dynstr section leaves a byte of padding between the old and
new data, but did not set it.  Make that NUL.
=> Fix uninitialized data in rewriter elf_update

symtabAPI/h/Aggregate.h, symtabAPI/h/Function.h, symtabAPI/h/Symbol.h, symtabAPI/src/Aggregate.C, symtabAPI/src/Function.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object.C, symtabAPI/src/Symbol.C, symtabAPI/src/dwarfWalker.C, symtabAPI/src/emitElf-64.C
The first commit adjusts INTERP in the program headers and section headers, to
account for added PHDR and the pagesize shift.  The second commit adds a debug
flag to Symbol so dwarf names can be easily excluded from the symbol tables.
Fixes #52.
=> Fix rewriting interp sections and debug symbols

proccontrol/src/linux.C
The sys/wait.h macros are expecting to operate on an int, and they have
some ugly pointer macros to deal with old BSD compatibility.  But we get
an unsigned long from PTRACE_GETEVENTMSG.  Normally this work out ok,
but on big-endian ppc64 those macros end up reading the int from the
most significant bits only, which are zero.
Cast the long down to a local int first, so WEXITSTATUS works properly.
Fixes #35.
=> Truncate PTRACE_GETEVENTMSG exit status to int

symtabAPI/CMakeLists.txt, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/emitElf.C, symtabAPI/src/emitElf.h
The emitElf64 source files were not being built globally on ELF systems, but only on 64-bit ones. This meant that 32-bit systems wouldn't link. Fixes #70.
=> Fix 32-bit build; rename emitElf64 to emitElf

dyninstAPI/src/dynProcess.C, dyninstAPI_RT/src/RTheap-linux.c, dyninstAPI_RT/src/RTheap.c, dyninstAPI_RT/src/RTposix.c
DYNINSTos_malloc in the RTlib would malloc its heap data structures and string processing data for /proc/maps. Both of these could lead to deadlocks with newer glibc versions. Fixed as follows:
1) mmaps are no longer trying to be smart, but instead asking the OS for something valid and bounds-checking it against the request
2) heap data structures are no longer malloced, but instead tacked onto the end of each heap segment
=> release9.2/bugs/rtheap_mmap_only

dataflowAPI/src/RoseInsnFactory.C
Define htobe on Windows/MSVC as a wrapper for _byteswap_ulong
=> Define htobe on Windows/MSVC as a wrapper for _byteswap_ulong

common/src/addrtranslate-win.C, stackwalk/src/win-x86-swk.C
Set defaults for Windows first-party stack walking: library tracker
=> Set defaults for Windows first-party stack walking: library tracker

.travis.yml
I thought that the llvm apt mirror being down was an temporary issue, but it seems to be going on for a while.
Disable building with clang for now.
=> Temporarily disable broken clang build

symtabAPI/src/emitElf.C
When .interp was in the first page, keep it there like the comment about
FreeBSD requires.  Just shift it for the new PHDR.  But if .interp is
already past the first page, as seen in libc.so for instance, then move
its offset a whole page like we do for every other section.  Then
program headers follow the same logic.
The conditional around startMovingSections and object type is totally
removed, as it did the wrong thing for PIE binaries which otherwise look
like shared libraries.  We now just move all sections except low interp.
Fixes #71.
=> Simplify INTERP logic for better consistency

symtabAPI/src/emitElf.C, symtabAPI/src/emitElfStatic.C
This commit aggregates the incremental fixes that Bill Williams and I
found while investigating issue #93, rewriting libc.so.
- The offsets of new sections need to account for library_adjust when
placing themselves after the first new section.
- TLS symbol values need *not* be adjusted, as they're section-relative.
- DT_INIT/FINI values need to be adjusted.
- x86 IRELATIVE relocations need their addends adjusted.
Fixes #93.
=> symtabAPI: Apply corrections for the library_adjust page offset

dataflowAPI/src/liveness.C
Cherry pick from `v9.2_patches`. This prevents buffer underreads if we have another situation where there is a register defined in `dyn_regs.h` for x86_64 that isn't defined in x86 but can somehow be used in 32bit mode.
=> Added asserts in liveness.C to prevent buffer underreads for

proccontrol/src/linux.C, proccontrol/src/loadLibrary/codegen.C
This fixes two cases where the low-level process was assumed to have a valid executable path, but it may not if a process was attached without ever specifying the exe.
- In `computeAddrWidth` we can rewrite the test to work with both big- and little-endian auxv.
- In `Codegen`, we can get the executable path from the `libraries()` pool instead.
Fixes #146
=> proccontrol: fix process attachment without an exe

symtabAPI/src/emitElf.C
In emitElf::createRelocationSections(), new relocations were calling
getGlobalRelType to determine their type.  However, this didn't take the
symbol type into account, so functions on PPC64 were getting GLOB_DAT
instead of JMP_SLOT, and they didn't work at all when called.
Each new relocationEntry already knows its type, so use getRelType().
=> symtabAPI: use the known type for new relocations

dyninstAPI/src/image.C, dyninstAPI/src/image.h
Less false positives on `findMain` dataflowAPI analysis. `findMain` now returns an int (0 on success, -1 on failure) instead of void. Some asserts have been taken out and replaced with return -1 (mutatee issues, not internal issues).
=> findMain improvements

dyninstAPI/src/codegen-x86.C
On RHEL6 with a prelinked `/lib64/libc-2.12.so`, all of tests involving
fork instrumentation were getting SIGSEGV in the mutatee.  This worked
in 9.1, and it also works fine after `prelink -u` to undo libc.  Using
git-bisect found 2b86eb4577bb as the point of regression.
It seems prelink ends up with libc sitting far away from the relocation
buffer, more than a 32-bit displacement, so `insnCodeGen::modifyData`
decides to rewrite that to a 64-bit immediate.  To do this, it has to
emit additional instructions first.  But after the commit above, part of
the rewritten instruction has already been written when we're trying to
emit those extras, and things gets clobbered.
This patch emits those preamble instructions first, before any part of
the newly rewritten instruction is copied out.
=> fix insnCodeGen::modifyData's 64-bit conversion

common/src/arch-x86.C
The intel developer manual specifies vpand as having operands "xmm1 xmm2
xmm3/m128". This change reflects this in dyninst.
=> Fix operand types for vpand

symtabAPI/src/Object-elf.C
Simple bare metal applications may not have a data segment.
=> symtabAPI: dont expect a data segment in elf; eliminate dead code

proccontrol/src/linux.C
Fixes one of the issues reported in #208, following up on #211.
If a thread exited at the wrong point in the middle of attach PC would throw errors where it should have handled it gracefully.
The actual parsing has been rewritten to hopefully be more robust, in a more modern style.
=> Fix errors when thread disappears during attach

proccontrol/src/int_process.h, proccontrol/src/linux.C, proccontrol/src/linux.h, proccontrol/src/process.C
When additional threads are found during the attach process, we should
synchronize to their stopping point, and check for new threads again,
until no new threads are found.  This keeps a more consistent state if
threads are racing to start while we're attaching.
=> proccontrol: Synchronize additional threads found during attach

dyninstAPI_RT/src/RTheap.c
An address passed to `mmap` is just taken as a hint, and the OS may
return something wildly different if that address is not available.
This is undesirable when we're trying to create a constrained alloc.
Now we will check that the address is in the requested range before
accepting it.  Otherwise, unmap it and try a new hint.
=> RT: trymmap should retry if the result is out of range

dataflowAPI/src/stackanalysis.C, dyninstAPI/src/BPatch_addressSpace.C, dyninstAPI/src/BPatch_type.C, dyninstAPI/src/function.C, dyninstAPI/src/image.C, dyninstAPI/src/inst-power.C, parseAPI/src/IA_powerDetails.C, proccontrol/src/DecoderWindows.C, symtabAPI/src/Object-elf.C
Fixed ppc build issues, and brought jump table handling to the point where it's broken because of tables that don't match our heuristics and a lack of ppc64 semantics, rather than a state where it can't possibly work.
=> Cleanup ppc (and old gcc) issues

proccontrol/src/process.C
If `int_thread::createThread` failed to actually attach to the thread,
it was leaving the thread object in the process in the `neonatal` state.
This failed assertions later when trying to stop all of the process's
threads, as it would have handler `stopped` and generator `neonatal`.
Now when a thread attach fails, it is set to `errorstate` and removed
from the active thread pools.  The assumption is that this thread simply
exited before we could attach, but we can't be sure of that without
having access to the ptrace return code (`ESRCH`).
=> proccontrol: scrub newly created threads that fail to attach

proccontrol/src/process.C
In the attach loop over waitfor_startup(), processes which fail are
erased from the set.  However, the iterator was getting incremented
again, which will skip the next process or even cause undefined behavior
if already at the end of the list.
With GCC 6.2.1, that UB manifested as an infinite loop on a self-
referential rbtree node.
The simple solution is to `continue` the loop after `erase(i++)`, as is
done in many other places with this same pattern.
=> proccontrol: fix double-increment while erasing a dead process

common/src/linuxKludges.C
Having sysctl kernel.yama.ptrace_scope=1, one may only call ptrace
attach on direct descendants.  The same restriction is also checked for
`process_vm_readv`/`writev` and certain procfs files.  However, if an
intermediate parent process already exited, we could end up with a
grandchild that we're still ptracing but isn't our descendant, so we
can't use the `process_vm` functions anymore -> `EPERM`.
We already had a fallback here for `EFAULT`, to just use `ptrace` memory
access, so use the same fallback after `EPERM` too.
Fixes #274.
=> common: use ptrace if yama blocked process_vm_readv/writev

cmake/packages.cmake
Dyninst would not build on the first run when libelf and libdwarf are not installed on the system.
=> Fix dependency of LibDwarf

dataflowAPI/src/stackanalysis.C
Wrap stackanalysis in a try-catch per function analyzed, and replace assertions with exceptions.
=> Remove stackanalysis assertions

elf/src/Elf_X.C
Dear Dyninst-team,
when building the path to separate files with debug information, the code omits leading zeros when concatenating hex bytes into a stringstream. (Problem is that setw() is not persistent). For example:
/usr/lib/debug/.build-id/d5/5c98c7fc69cfc0fc2504bc1df8a81fe7e255f9.debug <-- correct path
/usr/lib/debug/.build-id/d5/5c98c7fc69cfc0fc254bc1df8a81fe7e255f9.debug <-- path build in Elf_X::findDebugFile where the zero in the 0x04 byte is omitted.
=> Fix omitting leading 0's when concatenating hex bytes in stringstream

proccontrol/src/linux.C
After the commit 04d7e098f541769721d7511d56aea4b976fd29fd, in both 32-bit and 64-bit ARM kernels have the capability of tracing a syscall in the fast path as well (ie changing the flag during the syscall execution is allowed). Remove the workaround introduced as part of  commit 215d0f967a259cf883c903965ac490851e665170 .
cc @cuviper
=> arm64: remove syscall tracing workaround

dyninstAPI/src/image.C, parseAPI/src/IA_power.C
Fixed a couple of cases where I hadn't updated construction sites to account for lack of default args.
=> Update AssignmentConverter instantiation to make use of stack analysis explicit.

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
Dear dyninst team,
since DWARF3, static fields in C++ classes are represented by DW_TAG_variable entries and (newly added) DW_TAG_member entries. (Happened with GCC 6.2.1 here.) We found this note/issue on it: http://www.dwarfstd.org/ShowIssue.php?issue=161118.1
This seems not to be covered by dyninst yet when parsing structures: they are exposed as fields but with offset -1 in SymtabAPI. If I am not mistaken, fields exposed by SymtabAPI with offset == -1 can then be either constants or static fields.
As these fields are not part of the structures but global variables instead, we added a check to skip these newly added entries during DWARF parsing. What do you think about it?
We stumbled across this when parsing DWARF generated by GCC 6.2.1 from the following (the cyclic dependency was …
=> Enhance DWARF parser to recognize (and skip) DW_TAG_member entries for static fields

stackwalk/src/aarch64-swk.C, symtabAPI/src/relocationEntry-elf-aarch64.C
Not sure how first-party stack walking ever worked but it shouldn't have. Fixed now.
=> ARM64 fixes for stack walking

stackwalk/src/linux-swk.C, symtabAPI/src/dwarfWalker.C
Calling dwarf_srcfiles with error being NULL triggers an error when
deallocating. Fix it by adding an argument to dwarf_srcfiles.
Tested with libdwarf,
```
libdwarf.aarch64                     20161001-1.fc25                     @fedora
```
on Mustang. Please see for more technical background analyzed by William Cohen at:
```
https://bugzilla.redhat.com/show_bug.cgi?id=1316695
```
Unlike x86, Fedora 25 aarch64 still has an old version of libdwarf.
=> Fix test_basic test error

.travis.yml, cmake/Modules/FindLibElf.cmake, cmake/packages.cmake, common/h/IBSTree-fast.h
Dyninst 9.3.0 has two major problems:
1) Users were accidentally required to use the C++11 standard when building tools that use SymtabAPI, directly or indirectly.
2) While we removed libelf.so.0 support, our dependency infrastructure and CI settings would still try to use libelf.so.0.
Both of these are now fixed: we require libelf.so.1 to be present, and the spurious use of `auto` in public headers has been removed (along with some dead code).
=> Fixes for API and dependency issues in 9.3.0

parseAPI/src/BoundFactData.C, parseAPI/src/IndirectASTVisitor.C
A memory access to a known address should be considered as a variable, rather than a table read. So, the jump table analysis should not try to read the content of the variable, but try to determine whether the variable is bounded and used as a jump table index
=> Fix jump table analysis for lulesh 

cmake/packages.cmake, common/h/dyntypes.h, common/src/Types.h, dyninstAPI/h/BPatch_instruction.h, dyninstAPI/h/BPatch_memoryAccess_NP.h, dyninstAPI/src/BPatch_memoryAccess.C, dyninstAPI/src/Relocation/Transformers/Movement-analysis.C
Jenkins now has a `dyninst-build32` target using `CFLAGS=-m32`, but it needs this cmake fix to pass the flags to external projects.  I also cherry-picked the `Address`/`Offset` change from `v9.3.x`.
=> Support 32-bit builds in Jenkins

CHANGELOG.md, dyninstAPI/src/codegen-power.C, instructionAPI/doc/API/Instruction.tex
* Fix #356: ppc code generation should now consistently consider indirect branches as an option for long branching.
* Updated changelog
* Clarified InstructionAPI docs re: effective address expressions
=> Final cleanup bits for 9.3.2

common/src/addrtranslate-sysv.C
Ignore linux-vdso64.so.1, which is the vdso variant on some ppc64 linux.
=> Add linux-vdso64.so.1 to the library blacklist.

symtabAPI/src/Object-elf.C
Use the resolve function as the relocation function. (issue 396)
=> Handle R_X86_64_IRELATIVE relocation.

cmake/packages.cmake
Should fix #374. Caveat: this will use whatever toolchain is set in your environment for a boost build. Be sure a standalone boost build works in your environment before trusting this blindly.
=> Add FORCE_BOOST CMake option for @lee218llnl

symtabAPI/src/emitElf.C
This field used to contain verneednum, but now is hardcoded to 2.
This changes restores the original correct behavior.
Closes #405
=> Fix sh_info for VERNEED section

symtabAPI/h/Module.h, symtabAPI/src/Module.C
When used through BPatch_statement::filename() or various other internal code, the function Statement::getFile was causing memory errors.
This is because it returned a new string object that contains a copy of the string in the string map. If this copy is then just used to call .c_str and discarded, the returned pointer is dangling at the caller.
=> symtab: fix memory error in Statement::getFile

dyninstAPI/src/Relocation/Widgets/InstWidget.C
This fix is to address issue #455. When an unistrimentable point is selected for instrimenation
the behaviour Dyninst will now exhibit is the following:
1. InsertSnippet will return NULL if not in an insertion set and an illegal when parameter is used
2. If in an insertion set, InsertSnippet will return an object to the instrimentation. However when the set
is closed the insertion of that point will fail. It will either fail and continue to the next point (if
the insertion set closure is set to continue past errors) or roll back all prior insertions.
.
=> Fix for crashing on relocating at unistrumentable points

stackwalk/h/framestepper.h, stackwalk/src/framestepper.C, stackwalk/src/linuxbsd-x86-swk.C, stackwalk/src/sw.h
This patch contains a new walker that can walk out of inst frames in first party stackwalking mode.
For this to work, the emitter fixes located in pull request #451 must be applied. The walker itself creates
a Stackwalker frame based on the information saved by the emitter.
=> New walker to walk out of Instrimentation Frames FP

examples/CMakeLists.txt, parseThat/CMakeLists.txt
When USE_OpenMP=on, dyninst executables (parseThat and executables in examples) don't link without using -fopenmp as a link flag. Add this in the appropriate CMakeLists.txt files.
=> as needed, add -fopenmp flag when linking executables

instructionAPI/h/ArchSpecificFormatters.h, instructionAPI/h/RegisterIDs.h
Fedora installs dyninst includes into /usr/include/dyninst; thus any file included from within another dyninst include will not be found if the <HEADER> syntax is used since that syntax only searches system includes and /usr/include/dyninst is not a standard system include.  Using "HEADER" syntax (search same containing directory solves the problem.  There are only two cases of this so I'm guess it was an accident as opposed to an intentional decision.
=> Don't use system header <> syntax for dyninst includes

dataflowAPI/rose/util/Message.C, dataflowAPI/rose/util/Message.h
dataflowAPI/rose/util/Message.[Ch].  This was breaking the build when
using boost >= 1.69.
----------
The places where this fails is bizarre.  For example, this fails with
the message, "cannot convert 'boost::logic::tribool' to 'bool'".
```
boost::tribool tb;
bool b = tb;
```
However, adding an explict cast succeeds.  WTF!?
```
boost::tribool tb;
bool b = (bool) tb;
```
Also, g++ seems to be ok with an implicit conversion inside if().
(Again, WTF!?)  But I added an explicit cast for that case just to be
safe.
```
-      if (cs.bold)
+      if ((bool) cs.bold)
```
I think the above diff is not strictly necessary.  But it can't hurt
and it protects against some later compiler being more strict and
breaking this usage.
Also, from looking at the code in boost/logic, tribool certainly tries
to …
=> Add some explicit casts from boost::tribool to bool for some code in

parseAPI/h/CFG.h, parseAPI/src/Parser.C
Hi @mxz297 , I talked with John today. We thought that an "CodeSource provides no CodeRegions" doesn't indicate that we cannot use `CodeObject` and `CodeSource`'s interfaces to parse external sources, which is exactly we have done on the cuda code.
The changes in the newest commit perhaps makes the logic satisfy your requirement. If `_parse_state` is not unparsable, then we iterate every code region to check overlapped conditions and create a `OverlappingParseData` object. Otherwise, we create a `StandardParseData`.
=> Adjust Dyninst to support injecting CFGs for CUBINs

common/src/addrtranslate-linux.C, common/src/addrtranslate-sysv.C, common/src/pathName.C, common/src/pathName.h, common/src/serialize-bin.C, dyninstAPI/src/freebsd.C, proccontrol/src/linux.C, proccontrol/src/loadLibrary/codegen-freebsd.C
This fixes several bugs, adds a couple new features, and does a bit of cleanup. 70c9c93 contains a set of unit tests based on Catch2, and is not intended to be merged. It is here for discussion only. I will rebase it out when this is ready to be merged.
FIXED:
1. Tilde expansion is done _before_ the existence check.
Since `stat` does not do shell expansions, resolve_file_path("~")
always returned an empty string instead of the expanded path.
2. Tilde detection logic was inverted
3. Remove possible buffer overflow when making path relative to CWD
ADDED features:
1. Removes leading and trailing whitespace
2. Add basic support for Windows file system by using Boost::filesystem
Expansion of Windows-specific shell variables, e.g. %HOME%, is _not_
supported.
3. Leverage move semantics to reduce …
=> Fix several bugs in common/src/pathName.C

dataflowAPI/rose/semantics/DispatcherPowerpc.C, dyninstAPI/src/codegen-aarch64.C, dyninstAPI/src/codegen-x86.C, dyninstAPI/src/inst-x86.C, instructionAPI/src/InstructionDecoder-aarch64.h
Overflow of signed integer arithmetic (including shifting) is
undefined behavior in C++. Compilers are allowed to exploit
this UB for optimization purposes up to and including not
emitting any opcodes.
These were found using cppcheck.
=> Remove undefined behavior from bit-shifting code

symtabAPI/src/Symtab-edit.C
to behave abnormally due to duplicated symbols.
Note that adding symbols to .dynsym can be a legit use case, where
we expose hidden functions in shared libraries. But this use case
needs more development to support.
=> Do not put newly added functions to .dynsym, which may cause the load

cmake/packages.cmake
When building elfutils from source n systems that have old elfutils,
Dyninst couldn't find the correct version of elf.h due to it not
being copied from the elfutils build source directory to the include
directory. In the Feb 15 2019 release of elfutils, this flag was
added to fix this.
=> Add --enable-install-elfh when building elfutils from source

cmake/Modules/FindLibElf.cmake
Enforce the version check for the elfutils shared library. Add the Ubuntu-specific directories /usr/{lib,include}/x86_64-linux-gnu. Search for libelf.so instead of libelf.so.1 to increase likelihood of finding a symlink.
=> Elfutil version check

dyninstAPI/h/BPatch_binaryEdit.h, dyninstAPI/src/BPatch_binaryEdit.C, proccontrol/src/int_thread_db.C
This PR attempts to fix test failures listed in #550.
=> Attempts to fix legacy test failures in Dyninst test suite

dyninstAPI/src/inst-aarch64.C
This PR implements the following for **Dyninst AArch64 Rewriter mode**:
- Inter Module Function Address calculation
- Inter Module Function Call
- Inter Module Variable Address Calculation
- emitLoadShared
- emitStoreShared
- Move PC to Register
Description for IMFC can be found in #545 
Current limitations:
- Unable to spill and restore registers if none is available.
(on the current ARMv8 branch)
none of the rewriter passes. 
**With testsuite master branch:** 
```bash
for i in `seq 1 41`; do ./runTests -rewriter -test test1_$i; done
```
**30 out of 41** tests of group 1 pass, (with 6 fail, 5 crash) as in #545 
**With testsuite pic_fix branch:**
```bash
for i in `seq 1 41`; do ./test_driver -rewriter -g++ -test test1_$i; done
```
**33 out of 43** tests of group 1 pass, (with 2 fail, 8 …
=> Implement ARMv8 IMFC and Load/Store Shared

proccontrol/src/linux.C
This PR fixes a proccontrol hang on leela, but does not resolve a hang on ppcle. 
Even though this is not a complete fix, people are seeing test suite hang on all architectures. We should merge this PR soon and re-test all architectures.
=> Should set errno to zero before calling ptrace

cmake/cap_arch_def.cmake
By default, the cmake 'message' command generates an error message. This converts it to an informational message.
=> Convert ThreadDB error message to info message

proccontrol/src/int_thread_db.C, proccontrol/src/int_thread_db.h
On a machine without libthread_db.so, the placeholder class
had missing member functions and the contructors were calling
wrong base constructors.
=> Fix compilation of thread_db_process

common/src/dyn_regs.C, dataflowAPI/src/ExpressionConversionVisitor.C, dataflowAPI/src/RoseInsnFactory.C, dataflowAPI/src/SymEval.C
Remove assertions in code for translating Dyninst::MachRegister to ROSE Register. In addition, passing the error code back to jump table analysis. 
This PR is essentially for getting HPCToolkit working with a LLNL application.
=> Remove assertions for jump table analysis

dyninstAPI/src/inst-power.C
=> Fix BPatch_effectiveAddress on ppc where only low 32-bit address is extracted 

CMakeLists.txt
This is needed for FindBoost and is already in the Spack recipe
=> Bump minimum CMake version to 3.4.0

dyninstAPI/h/BPatch_snippet.h, dyninstAPI/src/BPatch_snippet.C, dyninstAPI/src/ast.C, dyninstAPI/src/ast.h, parseAPI/src/CFGModifier.C
The general problem is that when users use patchAPI to modify CFG, some of the modification is not properly updated in parseAPI data structures.
=> Fix bad interactions between patchAPI and parseAPI

dwarf/h/dwarfFrameParser.h, dwarf/h/dwarfHandle.h, dwarf/h/dwarfResult.h, dwarf/src/dwarfExprParser.C, dwarf/src/dwarfFrameParser.C, dwarf/src/dwarfResult.C, dyninstAPI/src/stackwalk-aarch64.C, stackwalk/src/dbginfo-stepper.C, stackwalk/src/linux-aarch64-swk.C
After porting Dyninst to use libdw, DwarfFrameParser missed dealing
with important Dwarf operations that would decode rules for findind
registers values. These rules were not properly decoded by Dyninst
decodeDwarfExpression, neither were being dealt by DwarFrameParser.
This fix properly retrieves libdw Dwarf operations and decodes them,
making it possible to DebugStepper work, which wasn't even before the
port, when lidwarf was being used on Dyninst 9.3.
Basically, Dwarf frame info can be a simple dwarf expression, representing
a value or a memory address, a location description, or a location list.
Libdw gives the consumer an array of dwarf operations that describes how
to find the value they're looking for, as opposed to libdwarf who gives
the consumer many out parameters that lead to …
=> Fix DwarfFrameParser, decodeDwarfExpression and DwarfResult

CMakeLists.txt, cmake/LibIberty.cmake, cmake/Modules/FindLibIberty.cmake, cmake/cap_arch_def.cmake, cmake/options.cmake, cmake/packages.cmake, cmake/shared.cmake
This brings the LibIberty dependency checker up to the new build system.
1. Fix build breakage when not specifying USE_GNU_DEMANGLER or IBERTY_LIBRARIES
=> Update LibIberty to new build system

instructionAPI/h/Result.h
Fix a problem on i686 and other 32 bit machines by using PRIx64 for long long.  The other snprintf could be likewise changed to use PRIxNN but long long is the only problematic one..
=> Use PRIx64 macros for long long results for i686.

instructionAPI/h/Result.h
This is a fix for #626 as the PRIx64 macros don't work on PPC before Power9.
=> Convert PRIx64 -> std::to_string

common/src/MappedFile.C, elf/src/Elf_X.C, symtabAPI/src/Object-elf.C
Ran into #436 myself, on a Debian system when opening `libc.so` with `Symtab::openFile`. This patch is essentially a corrected version of #487 (this version still opens the file ro, but also allows the mapped region to be rw).
Also fixes a similar issue that pops up when endianness conversions are needed (done in-place).
Steps to reproduce the issue:
0. Obtain a binary (`.../example.so`, although executables should work too) compiled with debugging info, and a small program (`./symopen`) that calls `Symtab::openFile` on said binary.
1. Generate a debug info file for the library: 
`objcopy --only-keep-debug --compress-debug-sections .../example.so borked.debug`
2. Add the debug link into (a copy of) the library: 
`objcopy --add-gnu-debuglink=borked.debug .../example.so borked.so`
3. Try …
=> Private writable mmap for opening binaries and debug files

symtabAPI/src/emitElf.C, symtabAPI/src/emitElf.h
This fix is making the update of the program headers in two passes. First,
we need to update the addresses, and then insert the new created segment.
This needs to be tested on all supported platforms on rewriter mode.
=> Fix overlapping bug of program header segments on fixPhdr.

cmake/ThreadingBuildingBlocks.cmake
When building with Clang, the minimum version required is now 2019.7 throughout.
=> Update handling of TBB CMake file for clang

cmake/Modules/FindLibElf.cmake
This adds the $INSTALL/lib/elfutils directory to the list of library locations during build. This directory contains the architecture-specific backends of elfutils.
=> Add 'elfutils' subdirectory to library paths

examples/CMakeLists.txt, parseThat/CMakeLists.txt
When linking the binaries for ParseThat and the examples, the transitive linkage between libsymtabAPI and libelf was not correctly resolved by the linker. Instead, it used the system libelf which may or may not be correct.
=> Add explicit ElfUtils dependency for ParseThat and examples

.gitignore
The instructionAPI/doc/.gitignore seems to be auto-generated when building the documentation. It tries to ignore instructionAPI/doc/API which is already in the git history, so it's best to just ignore it to
prevent its accidental inclusion.
=> Ignore additional Eclipse file and spurious .gitignore

symtabAPI/src/dwarfWalker.C
New encodings on dwarf sections .debug_info possibly introduced by gcc 8.* emerged.
DW_TAG_variable entries containing DW_AT_abstract_origin attribute were not being considered and therefore wrongly parsed.
=> Implements parsing of dwarf variables with abstract origin attribute.

common/src/debug_common.C, common/src/debug_common.h, symtabAPI/h/RangeLookup.h, symtabAPI/src/Object-elf.C
Come to fix the other issue in https://github.com/dyninst/dyninst/issues/625
Now the multi_index_container does not have a unique key for ranges, which allows the same range to be added for multiple source lines.
=> Allows same range for different source lines.

dyninstAPI/src/emit-x86.C
Fixes #582 
While I was not directly working to fix #582, this issue comes up and here is the fix.
=> Prevent corruption to rax during stack alignment on x86-64

symtabAPI/h/Type.h, symtabAPI/src/Type.C
Calling a member function of a base class before the base class's constructor has completed is undefined behavior.
I tried not to change `Type`'s API, but the member needed to be extracted in order to be handled during base class construction.
@mxz297 @blue42u Could you double-check that I didn't change the semantics?
=> Remove undefined behavior from Symtab::Type

dyninstAPI/src/codegen-aarch64.C
Fixes #721 
on platform aarch64.
=> Use register x30 (Link Register) to generate long branch

symtabAPI/src/emitElf.C
This should fix the problem of failed assertion in EmitELF.C when an unknown phdr_type is seen.
Fixes #743
=> remove unnecessary assertion for unknown phdr_type

parseAPI/src/CodeObject.C, parseAPI/src/Parser.C, parseAPI/src/Parser.h
In earlier PR for parallel parsing, I changed the parser to only populate the function list during parsing finalization, which makes it convenient to delete bogus functions created during parsing. However, for external code source such as CUDA, we will not invoke parsing or finalization. This causes hpcstruct to generate empty CFG.
This PR fixes the empty CUDA CFG problem by retaining functions from external source when the code object is told to not parse or cannot perform parsing.
=> Retain hint function from external source

proccontrol/src/handler.C, proccontrol/src/int_process.h, proccontrol/src/int_thread_db.C, proccontrol/src/linux.C, proccontrol/src/linux.h, proccontrol/src/process.C
Fixes #741
A "ghost" thread is one which has encountered an error when continuing
from a SIGSTOP. This can come about from the process being exited before
the SIGSTOP is handled.
@sashanicolas @mplegendre
=> proccontrol: Handle "ghost" threads

dyninstAPI/src/pcEventMuxer.C, dyninstAPI/src/pcEventMuxer.h
This cleans up handling of events from the mailbox (event queue) used to communicate between Dyninst and proccontrol.
This is rebased on #742
Closes #741
=> Fix proccontrol hangs in test_thread_X

symtabAPI/h/Aggregate.h
This was introduced in c848409ec, but never implemented.
=> Remove Aggregate::setModule declaration

dwarf/src/dwarfHandle.C, symtabAPI/src/dwarfWalker.C
Start using elfutils' libdwfl to open binaries with dwarf data.
This fixes dwarf variable location parsing for relocatable objects.
=> Fix Variable location parsing

proccontrol/src/int_process.h, proccontrol/src/linux.C, proccontrol/src/linux.h, proccontrol/src/process.C
Change plat_handle_ghost_thread to return 'bool' (see #742).
This indicates if the thread is actually a ghost or not. This can happen
because ptrace returned ESRCH (no such process) in
LinuxPtrace::ptrace_int, yet the process is alive. This is a valid state
for ptrace, but ptrace_int doesn't check for this. The ptrace man-page
indicates that this can happen when a process received a STOP signal,
but it hasn't transitioned to the new state yet.
=> Improve detection of ghost threads

dyninstAPI/src/pcEventMuxer.C, proccontrol/src/linux.C, proccontrol/src/process.C
This adds additional logging and enforces locking in PCEventMailbox::find.
=> Updates for #780

symtabAPI/src/emitElf.h
This is transitively included (somehow), but it's best to include it
directly both for completeness and for IDEs.
=> Add include for Elf_X in emitElf.h

symtabAPI/src/Region.C
The buffer is just a scratch space for doing work, and should not be
shared between Region objects. This was originally part of https://github.com/dyninst/dyninst/pull/317.
=> Fix Region::buffer aliasing bug on copy

CMakeLists.txt, dyninstAPI_RT/CMakeLists.txt
Remove DYNINST_RT_CMAKE_C_FLAGS which causes a mismatch when configuring dyninstAPI_RT with -pie
This is just the minimum patch.  It builds and links with the standard *_FLAGS.  I wonder about the if(BUILD_RTLIB)
loop step to allow building with a separate compiler.  I cannot foresee a situation on Linux where doing that is advantageous.
=> Fix cmake configuration with -pie

dyninstAPI/src/Relocation/DynObject.h
This is base class for dyninstAPI/mapped_object, so it should have a
virtual destructor.
Fixes #802
=> Make ~DynObject virtual

dyninstAPI/src/mapped_object.h
This was deprecated in 8442d36 in 2005. No reason was given, and it's being used in dyninstAPI/src/dynProcess.C:669.
closes #823
=> Undeprecate mapped_object::getBaseAddress

dyninstAPI/h/BPatch_flowGraph.h
This was deprecated in 71c302f in 2005. The code was commented out instead of being removed.
=> Remove deprecated members of BPatch_flowGraph

dyninstAPI/h/BPatch_snippet.h, dyninstAPI/src/BPatch_snippet.C
These were deprecated by 52f3437 in 2010.
closes #824
=> Remove deprecated BPatch_snippet::getCost*

dyninstAPI/h/BPatch_process.h, dyninstAPI/src/BPatch_process.C
This was deprecated by 4d83371 in 2011.
closes #825
=> Remove deprecated BPatch_process::enableDumpPatchedImage

dyninstAPI/src/addressSpace.C, dyninstAPI/src/addressSpace.h, dyninstAPI/src/binaryEdit.C, dyninstAPI/src/binaryEdit.h, dyninstAPI/src/dynProcess.C, dyninstAPI/src/dynProcess.h
This was originally part of https://github.com/dyninst/dyninst/pull/317.
@wrwilliams Could you provide some rationale why this was done? It's a fairly blunt change since both `PCProcess` and `BinaryEdit` are part of the public API. Also, there are other examples where this kind of transformation could be applied: `common/SymReader` and `ParseAPI/InstructionSource`, for example. Should this kind of refactoring be propagated elsewhere?
=> Remove AddressSpace::getAddressWidth from public API

dyninstAPI/src/addressSpace.C, dyninstAPI/src/addressSpace.h, dyninstAPI/src/binaryEdit.C, dyninstAPI/src/binaryEdit.h, patchAPI/h/Command.h
This was originally part of https://github.com/dyninst/dyninst/pull/317.
This is an API-breaking change since AddressSpace is exported through the BPatch interface.
=> Fix memory leak of AddressSpace::patcher_

dyninstAPI/h/BPatch_addressSpace.h, dyninstAPI/src/BPatch_addressSpace.C, dyninstAPI/src/BPatch_frame.C
This was deprecated by 7f20129 in 2010. Users should instead use either BPatch_addressSpace::findFunctionByEntry or BPatch_addressSpace::findFunctionsByAddr.
Closes #820
=> Remove BPatch_addressSpace::findFunctionByAddr

common/src/singleton_object_pool.h, instructionAPI/src/InstructionDecoder-aarch64.C, instructionAPI/src/InstructionDecoder-aarch64.h, instructionAPI/src/InstructionDecoder-power.C, instructionAPI/src/InstructionDecoder-power.h, instructionAPI/src/InstructionDecoderImpl.C, instructionAPI/src/InstructionDecoderImpl.h
Two memory leak fixes related singleton_object_pool.
1. The singleon_object_pool currently only destructs objects but does not deallocate memory space. This leak applies to all architectures.
2. On ppc and arm, instruction decoder does not use smart pointers to manage InstructionAPI::Instruction constructed by a singleon_object_pool, and thus cause memory leaks.
=> Fix memory leak in singleton_object_pool

common/h/dyntypes.h, common/h/util.h, dataflowAPI/rose/semantics/MemoryMap.h, dataflowAPI/rose/util/Exception.h
They were deprecated in c++11 and removed in c++17.
closes #708
=> Remove exception specifications

common/h/dyntypes.h, common/h/entryIDs.h, instructionAPI/h/RegisterIDs.h
Require std::unordered_{map,set} for dyn_hash_{map,set}, and convert the dyn_hash_* macros to alias templates for better type safety and error messages. Remove the custom hashers, and use typed enums for IA32Regs, entryID, and prefixEntryID.
=> Cleanup dyn_hash_{set,map}

dyninstAPI/src/mapped_object.C, instructionAPI/src/ArchSpecificFormatters.C, instructionAPI/src/Register.C
Starting in C++11, it is undefined behavior to have the destination
iterator be contained within the input range.
=> Fix undefined behavior in usage of std::transform

common/h/Buffer.h, common/h/DynAST.h, common/h/SymReader.h, common/h/dyntypes.h, common/h/entryIDs.h, common/src/arch-power.C, common/src/arch-power.h, common/src/util.C, dyninstAPI/src/codegen.h, symtabAPI/h/symutil.h
This prevented using concurrent data structures in dyntypes.
=> Remove include cycle in dyntypes.h

dyninstAPI/src/binaryEdit.C, dyninstAPI/src/binaryEdit.h
This moves the same functionality into the destructor and prevents possible memory corruption when its usage would promote in-place object reuse. Originally part of #317.
=> Remove binaryEdit::deleteBinaryEdit

dyninstAPI/src/addressSpace.C
`deleteAddressSpace` is still highly suspect because its only use is `copyAddressSpace` which doesn't fully copy the object. However, this fix at least makes `deleteAddressSpace` and `~AddressSpace` correct and perform the same actions.
This was originally part of #317.
=> Correctly destruct AddressSpace objects

dyninstAPI/src/parse-cfg.h
This fixes a memory corruption bug when destroying default-constructed objects of this class.
=> Provide correct default constructor for parse_func class

dyninstAPI/src/binaryEdit.h
This gives explicit copy and move semantics to the class and uses a std::unique_ptr to manage the contained buffer. Construction is also simplified by always using calloc.
=> cleanup memoryTracker memory handling

dyninstAPI/src/block.h, dyninstAPI/src/unix.C
Sometimes, the PLT address and the CFG target aren't the same (e.g., Intel's CET causes this), so we just look up by name.
Fixes #852
=> Add lookup by name in block_instance::callee

parseAPI/h/CFGFactory.h, parseAPI/src/CFGFactory.C
This removes the possiblity of object reuse and its associated undefined
behavior. This was originally part of #317.
=> Remove CFGFactor::destroy_all

dyninstAPI/src/unix.C
This was originally part of #317
@wrwilliams 
1. I didn't use SymElfFactor::openSymbolReader from the original fixes in #317 because it adds a link dependency to unix.o. Instead, I used a lambda with admittedly funky semantics.
2. For the static executable case, previously only the first archive member was checked. If it was not a compatible binary, the retMap was cleared (approx. line 605 in c0acebbe7). Now, all members are checked, and the retMap is never cleared. Is this a significant algorithmic change?
@mxz297 
Could you take a close look at dca0e46f3 to make sure I didn't inadvertently change the overall behavior?
=> Fix memory leaks in BinaryEdit::openResolvedLibraryName

parseAPI/h/CodeSource.h, parseAPI/h/SymLiteCodeSource.h, parseAPI/src/CodeSource.C, parseAPI/src/SymLiteCodeSource.C, parseAPI/src/SymtabCodeSource.C
This ensures that CodeSource is responsible for cleanup up its own objects rather than relying on the derived class to do it. This is particularly important since this class is part of the pubic API.
This was originally part of #317
=> CodeSource destructor cleanup

dyninstAPI/src/Relocation/CodeTracker.h
This only showed up in gcc-10. I'm assuming they fixed some transitive includes in libstdc++.
=> Include <iostream> in CodeTracker.C

dataflowAPI/h/Absloc.h, dataflowAPI/h/AbslocInterface.h, dataflowAPI/h/slicing.h, dataflowAPI/src/AbslocInterface.C, dataflowAPI/src/slicing.C
1. Change pass-by-value arguments to pass-by-reference.
2. Pre-allocate vector/map entries to avoid redundant copies.
3. Use hash map for slicing cache.
=> Improve single thread's backward slicing speed by 40%

cmake/Modules/FindLibIberty.cmake, common/src/symbolDemangle.c
Some platforms don't install libiberty in a subdirectory (e.g., /usr/include/libiberty), so account for that.
=> Make libiberty detection more flexible

common/src/dyn_regs.C
As title, the previous implementation of adding support for the name of amdgpu register vector is buggy, and I fix it so now it displays the correct register names. 
I thought I only modify a single file since my last commit that should have been merged in #900 , but I don't know why all my previous commits show up in this pull request
=> Fix a bug in MachRegister::name function

patchAPI/src/Point.C
When an edge is direct branch or conditional taken branch, and it is inter-procedural, we consider it as a direct tail call and return the target of this edge as the callee.
=> Add direct tail call case for getCallee

cmake/LanguageStandards.cmake
We've quietly required the ABI and API changes in libstdc++ for some time, but we make them explicit now.
=> Require gcc >= 6.0

symtabAPI/h/Symbol.h, symtabAPI/src/Symbol.C
The following methods should be const methods of the class Symbol:
- getVersions
- getVersionFileName
- getVersionNum
- getVersionHidden
- getReferringSymbol
Fixes: #935
=> make Symbol methods const

dwarf/src/dwarfHandle.C
As title, fixing a bug in DwarfHandle::init_dbg where the arch is not set and wrong value is returned for Arch_amdgpu_vega and Arch_amdgpu_rdna
Fixes #937
=> Fix wrong return value in DwarfHandle::init_dbg

common/h/concurrent.h, symtabAPI/doc/API/Symtab/Module.tex, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Module.h, symtabAPI/h/Symtab.h, symtabAPI/src/Module.C, symtabAPI/src/Object-nt.C, symtabAPI/src/Symtab-edit.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C, symtabAPI/src/dwarfWalker.C
- changed findVariableByOffset that returned a Variable
to      findVariablesByOffset that returns a vector of Variables
- changed Symtab::varsByOffset to map an offset to a vector of
variables each with a unique size.
- added undefined method Module::findVariablesByOffset
Fixes #933
=> Aggregate variable symbols based on offset and size

common/src/dyn_regs.C, instructionAPI/src/InstructionDecoder-amdgpu-vega.C, instructionAPI/src/InstructionDecoder-amdgpu-vega.h, instructionAPI/src/amdgpu_decoder_impl_vega.C, parseAPI/src/IA_amdgpu.C, parseAPI/src/SymbolicExpression.C
This commit should fix most of the compile warnings mentioned in #952  except -Wunused-parameter
The fix involves:
Reorder the C++ initializer list to get rid off reorder warnings
Removing unused functions copied from InstructionDecoer-aarch64.C
Unused variable commented out in amdgpu_vega_impl.C
Add cases to handle the yet-to-be-supported Arch_amdgpu_rdna in dyn_regs.C
Fixes #952
=> Fix compile warnings for AMDGPU for Release 11.0

symtabAPI/h/Collections.h, symtabAPI/src/Collections.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-nt.C, symtabAPI/src/dwarfWalker.C, symtabAPI/src/parseStab.C
This was removed by a8def5c64b5 in 2017
@wrwilliams Why does `Collections::addGlobalVariable` use the name from the `Type`'s constructor, but [`BPatch_typeCollection`](https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/BPatch_collections.h#L101) uses the user-provided one?
=> Remove unused 'name' parameter from Collections::addGlobalVariable

common/CMakeLists.txt
On some platforms, the libiberty headers are not in the usual place. The user can override the location in CMake, but this path is ignored by the CMakeLists.txt
=> add missing libiberty include dir

symtabAPI/src/Object-elf.C
The final `const` was always ignored.
=> Fix cast qualifiers in Object-elf::read_val_of_type

dwarf/src/dwarfHandle.C
Designated initializers aren't part of C++ until C++20; use aggregate initialization, instead. This also fixes the missing initializer for Dwfl_Callbacks::debuginfo_path.
=> Remove usage of designated initializer in dwarfHandle.C

common/src/arch-power.C, common/src/arch-power.h
This is undefined behavior in C++.
=> Fix shifts of negative values

common/src/Time.C
The current implementation causes several -Wstringop-truncation warnings. Yet, the whole thing can be replaced by using locales.
=> Use std::locale when writing a timeStamp to a stream

parseThat/src/config.C, parseThat/src/parseThat.C
For some reason, these didn't show up when fixing those in #967.
=> Fix C-string truncations in parseThat/config.C

symtabAPI/h/Aggregate.h, symtabAPI/src/Aggregate.C
The previous declaration relied on header inclusion ordering to be correct. The following example program failed to build:
#include "Function.h"
int main(){}
=> Correctly declare Aggregate::operator<<

parseAPI/src/Parser.C
This function call has side effects that were not properly tested for before committing PR990.
=> Fix breakage introduced by PR990

cmake/Boost.cmake
This is needed because we no longer support the headers deprecated in that version. See also #974
=> Bump minimum Boost version to 1.67

dyninstAPI/src/Relocation/Transformers/Movement-adhoc.C
=> Add the default case in adhocMovementTransformer::isPCRelData to suppress compiler warning

common/src/arch-x86.C
The STUB_OUT_TO_AVOID_RACE was added by 43dd5eb6eb in 2018. It's never set, so this entire calculation is never used.
=> Remove dead code from ia32_decode

dyninstAPI/src/unix.C
This was introduce by 14b6941fc in 2020 (PR #875). This fix allows both types of lookup by name, but preserves the "return NULL if not found" semantics of block_instance::callee().
=> Remove assert in block_instance::callee(std::string const&)

dyninstAPI/src/Parsing.C
This is purely an adaptor to account for Symtab::Function(Symtab::Symbol*) being protected.
@mxz297 I don't think this will affect #1001 as the usage there is polymorphic to `Symtab::Function`. But just in case, can you rebase your branch on this change?
=> Clean up PLTFunction class from dyninstAPI/Parsing.C

dyninstAPI/src/Parsing.C, dyninstAPI/src/image.C, dyninstAPI/src/image.h, dyninstAPI/src/unix.C
BPatch creates additional SymtabAPI::Function objects for PLT stubs but does not put these SymtabAPI::Function objects back to Symtab objects. Later BPatch look up function callees through the Symtab object and cannot find PLT stubs.
This PR records functions created for PLT and fix the lookup.
=> Fix PLT function call lookup

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
when a dwarf type entry, not yet parsed, is encountered.
=> In DwarfWalker, start a new context dissociated from the current context

CMakeLists.txt
Set the build directory (-B) and source directory (-S) when
configuring dyninstAPI_RT
This simple change configures out of source tree correctly for dyninstAPI_RT on
(Fedora release 33)
cmake version 3.19.7
(without the change: Build files have been written to: /work/scox/dyninst/src/dyninstAPI_RT)
=> Set -B and -S when configuring dyninstAPI_RT

dyninstAPI/src/addressSpace.C, dyninstAPI/src/addressSpace.h, dyninstAPI/src/binaryEdit.C, dyninstAPI/src/dynProcess.C, dyninstAPI_RT/src/RTposix.c
Add a new environment variable `DYNINST_SIGNAL_TRAMPOLINE_SIGILL` to control whether we use SIGILL as the signal for trampolines.
If `DYNINST_SIGNAL_TRAMPOLINE_SIGILL` is set, we use SIGILL as signal trampolines and the mutator will generate illegal instructions in the mutatee.
In the case of binary rewriting, `DYNINST_SIGNAL_TRAMPOLINE_SIGILL` should be consistently set or unset when rewriting the binary and running the rewritten binaries.
=> Allow usage of SIGILL for signal trampolines

parseAPI/src/SymtabCodeSource.C
This PR aims to fix a hpcstruct segfault reported by a user (https://github.com/HPCToolkit/hpctoolkit/issues/403).
ParseAPI will assert when parsing a binary compiled on Lassen. The root cause of the problem is that PLT stubs in the binary are marked as NOTYPE and they are inside .fini section rather than .plt section. This causes ParseAPI to treat these symbols as data rather than code.
=> Do not treat symbols in any text sections as data

symtabAPI/src/Object-elf.C
The root cause is that SymtabAPI uses a 8-byte value to read catch block addresses, which can be a 2, 4 or 8-byte value. While we are careful to clip the value when reading it, there is an addition to it later where we did not clip the value according to its size.
Fixes #1027
=> Fix catch block parsing

common/src/debug_common.C, common/src/debug_common.h, common/src/dyn_regs.C, dataflowAPI/src/AbslocInterface.C, parseAPI/src/JumpTableFormatPred.C
As title, there is one lingering debug cout that causes large output as mentioned in the issue #1028 
closes #1028
=> Remove Debug Cout that causes large output

parseAPI/src/Parser.C
=> Skip parsing of blocks whose code buffer is null

dataflowAPI/src/RoseInsnFactory.C
Remove the use of structured binding as it is a C++-17 feature.
Fixes #1031
=> Remove the use of C++17's structured binding

cmake/Modules/FindTBB.cmake
2020.1.1 renamed 'tbb_stddef.h' to 'version.h'
Fixes #1039
=> Search for 'version.h' when determining version for TBB

dyninstAPI/src/dynProcess.C, dyninstAPI/src/image.C, dyninstAPI/src/image.h, dyninstAPI/src/mapped_object.C, dyninstAPI/src/pcEventHandler.C, dyninstAPI/src/unix.C, proccontrol/src/sysv.C, symtabAPI/doc/API/Symtab/Module.tex, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Symtab.C
All functions that determine if an object is a shared library and/or an
executable are now based on a single set of functions in Object-elf.
This make all the functions in the various Dyninst libraries and classes
consistent and also makes Dyninst correctly handle PIE executables.
These functions in Object-elf are based on functions found in elfutils's
elfclassify program (with small improvements to better determine if a
shared library is also an executable).   The new functions in Object-elf
include:
* isOnlyExecutable()
* isExecutable()
* isSharedLibrary()
* isOnlySharedLibrary()
* isLoadable()
* isDebugOnly()
* isLinuxKernelModule()
Symtab exposes some of these functions through its public API.  isExec()
now correctly handles PIE executables, and two new functions were added
to …
=> fix Position Independent Executable (PIE) handling

instructionAPI/src/Operation.C
=> Fix implicit operand decoding of x86 instructions on non-x86 architectures

dyninstAPI/src/BPatch_frame.C
=> BPatch_frame::findFunction - find function by address, not by entry

symtabAPI/h/Type.h, symtabAPI/src/Type.C, symtabAPI/src/dwarfWalker.C
These properties are needed for doing ABI analysis in Smeagle.
ping @vsoch
=> Add DWARF4 base type entry encodings to symtabAPI::typeScalar

symtabAPI/h/Module.h
It was declared by c848409ec9 in 2009, but never defined.
closes #635
=> Remove Module::getAllVariables

dyninstAPI/src/inst-aarch64.h
The macro for the TRAMP_*_OFFSET_32 cases expanded into `({assert(0); 0;})` which is not legal C++. It was allowed by gcc by extension. Converting them to functions preserves the behavior without code changes. They are made `inline` to prevent ODR violations.
ping @kupsch
=> Convert TRAMP_*_OFFSET macros to functions for aarch64

cmake/warnings.cmake, common/h/compiler_annotations.h
- detect warning flag test failure on clang correctly by updating the failure regular expression to include clang's unknown warning flag message
- fix c preprocess macro tests for scoped attributes in C
Fixes #1091
=> fix compiler warnings to work with clang

dyninstAPI_RT/src/RTspace.S
This prevents the library/object with this code from having a segment violates
the W^X security property for segments as the current setting resulted in
segment with both the WRITE and EXECUTE flags set.  The function
mark_heaps_exec() restores execute protection to just the heap arrays.
Tested and no regressions on X86_64, ARM and POWER
.
Fixes #1094
=> remove executable flag from .dyninst_heap section

cmake/LibIberty.cmake
This correctly requires that libiberty be present and removes building it from source. Both of these were bugs introduced by 08097f23.
Closes #1098
=> Enforce detection of libiberty

cmake/cap_arch_def.cmake, common/CMakeLists.txt, proccontrol/CMakeLists.txt, symtabAPI/CMakeLists.txt
The Compute Node Linux (CNL) was for the old Cray XT/XE platforms that
are obsolete now. This should have been removed by e5484368f in
2021. Support for this platform was removed from the test suite by
7e4ab7c12 in 2012.
Closes #1133
=> Remove support for Cray CNL

cmake/cap_arch_def.cmake, dataflowAPI/src/ABI.C, dyninstAPI/src/addressSpace.C, dyninstAPI/src/inst-x86.C
Currently, this is used in several different ways due to the historical
original meaning drifting over the years. It's meaning is now "this host
64-bit platform supports modifying 32-bit binaries". Currently, this is
only x86 and PPC32. Although the latter is going away soon due to
obsolescence.
Requires https://github.com/dyninst/testsuite/pull/202
=> Unify meaning of 'cap_32_64' macro

common/src/dyn_regs.C
Previously, ROSE didn't support ppc64, so the ppc32 registers were used.
@mxz297 The only piece I'm not sure about is `baseID = reg & 0x0000FFFF;`. This was being used for ppc64 previously, so I'm assuming it's ok. Could you verify?
=> Implement ppc64 in MachRegister::getROSERegister

dwarf/src/dwarfResult.C, dyninstAPI/src/ast.C, symtabAPI/src/dwarfWalker.C
wrap macro body in 'do {...} while (0)' so they can be used as if they were a
statement with a terminating semicolon.
=> fix statement-like macros

parseAPI/doc/API/CodeObject.tex
Add wording to improve clarity about when a CodeRegion is strictly needed when using the lookup functions.
Closes #1102 
@wcohen @mxz297
From poking around in the code, it looks like the only place that the ParseData interface is exposed is through member functions in CodeObject. I think that's the best place to document this.
The interface for ParseData is
1. Function * findFunc(CodeRegion *, Address);
2. Block * findBlock(CodeRegion *, Address);
3. int findFuncs(CodeRegion *, Address, set<Function*> &);
4. int findFuncs(CodeRegion *, Address, Address, set<Function*> &);
5. int findBlocks(CodeRegion *, Address, set<Block*> &);
6. ParseFrame * findFrame(CodeRegion *, Address);
7. ParseFrame::Status frameStatus(CodeRegion *, Address addr);
8. void …
=> Improve docs for lookup functions in CodeObject

CMakeLists.txt
There is a bug in 3.19.0 that treats .S files like C-language files. I have tested every version of CMake from 3.18.0 to 3.24.1 (the latest as of now), and each of them is able to configure, build, and successfully execute the test suite without any regressions.
Closes #924 
Fixes #923
=> Add conflict with CMake 3.19.0

symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
findDieName always returned 'true', so any checks for its return value
were meaningless. It was also not clear that 'findName' would modify its
argument. The new interface removes that surprise by making the name the
return value.
=> DwarfWalker: clean up interfaces for findDieName and findName

symtabAPI/src/dwarfWalker.C
Arguably, this is completely arbitrary as it could have been spelled
'ref', 'reference', etc. Using the language symbol also allows users to
reconstruct source-level syntax more directly.
Fixes #1050
=> Add readable name for Symtab::typeRef

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
This function always returns 'true' and few callsites checked the bool
out variable. Using an optional here makes everything simpler. Logging
has been substantially improved for better tracing. The function was
renamed to better indicate its behavior.
=> Refactor dwarfWalker::findValue

cmake/ElfUtils.cmake
This is needed to parse NVIDIA's extended line map information.
HPCToolkit makes extensive use of this functionality.
=> Increase minimum elfutils version to 0.186

dyninstAPI/src/binaryEdit.C, dyninstAPI/src/binaryEdit.h, dyninstAPI/src/codeRange.h
This was originally part of #317
=> Clean up memoryTracker usage in binaryEdit

.github/workflows/base-containers.yaml, CHANGELOG.md, README.md, docker/Dockerfile, docker/README.md, docker/build.sh
This is the first of two PRs to add automation to Dyninst, including:
- a container base that can be used for Dyninst development or app development using dyninst
- the same container base that provides a much quicker way to test (3.5 minutes vs 45-1hour to build from scratch)
This first PR will add the automated build for the base container, which we can leave to also build on PR, but would be okay to remove and just have build on push to main and scheduled nightly (what I recommend). The second PR after this will be to add another workflow to use this base container to run tests.
The base container uses ubuntu 20.04 and a set of dependencies chosen by Tim.  Currently this does not upload test results to Tims server, and this is only because I want to talk to him about it first and then …
=> Adding first stage of automated docker build

.github/workflows/base-containers.yaml
To release a tagged (versioned) container on publication of a release we just need to add the release -> published trigger, derive the tag from the GITHUB_REF environment variable, and then tag and push the container.
cc @hainest 
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Adding dyninst release trigger

dyninstAPI_RT/src/RTlinux.c
Previously there was a dynamic relocation against _r_debug in the loader which picked up the interposed definition,
but glibc now uses a direct internal hidden symbol reference and thus no longer updates the interposed object.
=> Remove interposed definition of _r_debug

parseAPI/h/CFG.h, parseAPI/src/Block.C, parseAPI/src/Parser.C
In some binaries a single function has many callers, so copying out the source edges for the entry Block takes a while and causes significant contention on the Block's lock. The case in Parser::finalize where this becomes a hotspot likely does not need to read every edge, so this commit inlines those cases into methods on Block instead.
=> ParseAPI: Speed up the many-called function case

.github/workflows/base-containers.yaml, docker/Dockerfile
This is a test to fix the current build failure of the base container. Spack had a PR merged in < 24 hours ago that allowed gettext to be added as an external dependency - and this seems to be what is triggering the error. This test will uninstall gettext before doing the spack find and hopefully will fix the error.
The build takes ~1 hour and if it works we can remove the PR trigger.
This will close #1194
=> Dockerfile: use explicit packages for 'spack external find'

dyninstAPI_RT/src/RTlinux.c, symtabAPI/src/emitElf.C
When the symbol table is created in
emitElf<ElfTypes>::createSymbolTables, also update the elf _DYNAMIC
symbol to reflect the new address of the .dynamic section.
I did this with regard to issue 1155 (which has a simpler solution).  But it seems reasonable to keep _DYNAMIC up to date.  PT_DYNAMIC in phdr is kept up to date by fixPhdrs.
Fixes #1155
=> glibc r_debug extensions to support multiple namespaces

dyninstAPI/src/IAPI_to_AST.C, dyninstAPI_RT/h/dyninstRTExport.h
This should have been removed by #1146 (0b9df83c9).
Fixes #1166
=> Additional cleanup of memory emulation for hybrid analysis

dyninstAPI/src/BPatch.C, symtabAPI/h/Type.h, symtabAPI/src/Type.C, symtabAPI/src/dwarfWalker.C
This contains substantial updates to the correctness, capability, and interfaces for SymtabAPI::typeEnum. These changes necessarily break the ABI.
Closes #1079 
@mxz297 @kupsch @bigtrak I carefully broke these changes down into the smallest commits possible, made sure each would build and execute, and wrote as much supporting documentation in the commit messages as possible. Some of these changes fundamentally alter how users interact with this type. This is necessary in order to ensure class invariants for the type information in the derivedType interface. I think it would be a good long-term goal to clean up the interfaces for the rest of the types in Type.h, but we can do that as we make other changes to those classes.
=> Improve DWARF enum parsing in Symtab::Type

symtabAPI/h/Type.h, symtabAPI/src/dwarfWalker.C
Fixes #1049
@kupsch @bigtrak @mxz297 Technically, this doesn't break ABI even though the size of the `typeRef` class changed because Symtab always refers to this type through a pointer. It does have the capacity to break user code if someone had a function taking a `typeRef` by value. I think making a note about this in the release notes is good enough. Thoughts?
=> SymtabAPI::Type: add support for C++ r-value references

common/CMakeLists.txt
With this commit, the common/h/AMDGPU headers will be installed to the correct path and should fix the issue that was reported in #1198
=> Add install rule to install headers under common/h/AMDGPU

instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.C, instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.h, instructionAPI/src/AMDGPU/cdna2/amdgpu_cdna2_decoder_impl.h
These are just a few items picked up from static analysis. Some of them should have been compiler warnings (e.g., uninitialized class members).
=> Tidy up classes in AMDGPU

docker/Dockerfile
@vsoch After using the container a bit, I've had a substantial change of mindset. Using more OS packages is really necessary to get the build times down to something reasonable. The versions aren't as important as I thought they were going to be when we were first writing this. I've tested these changes end-to-end and both Dyninst and the test suite build fine. The only part I was unsure about was the view created for cmake and perl. Now that those are used as external packages, it didn't seem to be necessary to set them up as views. Am I understanding that correctly?
=> Docker: use more OS packages

symtabAPI/src/dwarfWalker.C
This isn't part of DWARF4 or DWARF5.
=> Remove usage of DW_AT_MIPS_linkage_name

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
- fix valid pc address ranges for local variables that are declared in a
sub-block (brace, try and catch blocks) of their function
- fix Context class's constructors so they correctly initialize and copy
all member (use in-class initialize and default constructors)
Fixes #1225
=> Correctly propagate pc ranges for blocks and local variables

CMakeLists.txt, cmake/options.cmake
When not enabled, the dyninstAPI_RT/cmake_install.cmake isn't present. This has been broken since it was implemented by e1afc6918 in 2016.
Fixes #1228
=> Remove BUILD_RT option

common/src/concurrent.C
gcc allows this as an extension by considering sizeof(void) to be 1 (http://gcc.gnu.org/onlinedocs/gcc/Pointer-Arith.html).
Fixes #1227
=> Remove void pointer arithmetic when using Valgrind annotations

.github/workflows/base-containers.yaml, docker/Dockerfile
This should have been part of #1211
=> Docker: use more OS packages for dependencies

docker/Dockerfile, docker/Dockerfile.test, docker/build.sh, docker/test.sh
We want to use -Werror to catch any warnings introduced by code changes. However, the test suite isn't ready to be built that way, so we use the external-tests instead.
=> Docker: use external-tests instead of testsuite in base image

.github_changelog_generator, .gitmodules
.gitmodules hasn't been used since the test suite was moved to its own repository.
.github_changelog_generate hasn't been used since v10.0.0
=> Remove unused git files

cmake/optimization.cmake
The gold linker crashes and is no longer supported.
Fixes #1230
Fixes #676
=> Use bfd linker for LTO

stackwalk/src/callchecker.C
These are only present when SW_ANALYSIS_STEPPER=OFF.
Fixes #1233
=> Fix format string errors in stackwalk/callchecker.C

parseAPI/src/Parser.C
When multiple functions share code and include a tail call, and when the tail call is first wrongly identified, during finalization, and one of the multiple function will correct the tail call and recompute its function boundary, other functions will still have the wrong function boundaries. This PR fixes this issue.
=> Redo finalization to get correct function boundaries

dyninstAPI_RT/src/RTheap-linux.c, dyninstAPI_RT/src/RTheap.c, dyninstAPI_RT/src/RTlinux.c, dyninstAPI_RT/src/RTposix.c, dyninstAPI_RT/src/RTsignal.c
- replace feature test macro _GNU_SOURCE with _DEFAULT_SOURCE
to support older version of glibc
Fixes #1251
=> Fix dyninstAPI_RT files to build with older glibc

CMakeLists.txt, cmake/options.cmake
We should revisit using CPack.
=> Remove unused build options

docker/Dockerfile
The public keys have been removed.
=> Docker: don't use autamus cache

common/src/dyn_regs.C
Add a missing case to MachineRegister::DwarfEncToReg for Arch_intelGen9 that returns Dyninst::InvalidReg instead of reaching the default case with an assert. 
This change was necessary to swallow DWARF variable information for Intel GPUs, which HPCToolkit ignores.
=> add case in DwarfEncToReg for Arch_intelGen9

cmake/Modules/FindLibIberty.cmake
This was originally part of #1263
Co-authored-by: Jonathan R. Madsen <jrmadsen@users.noreply.github.com>
=> Fix bug in processing library paths in FindLibIberty.cmake

cmake/endian.cmake, cmake/shared.cmake
The usage of the macros was removed by d233ae759 in 2020.
Support for big-endian platforms was removed by 481abaf204 in 2021. There is a larger change of removing endian checks throughout the code base.
=> Remove endian CMake check

symtabAPI/src/LineInformation.C, symtabAPI/src/Object-elf.C
- Boost multi_index_set is not thread safe. Add an OpenMP critical section to guard against parallel inserts. 
- Is this enough? A more comprehensive fix would be to add a reader/writer lock and also synchronize reads of this structure.
- dwarf_next_lines uses calls code that uses glibc's tsearch, which is not thread safe. A better fix would be to replace or synchronize the use of tsearch in elfutils. 
NOTE: in practice, these fixes led to safe parallel analysis using 16 threads of a 240MB LLNL export-controlled cubin that can't be used externally for testing.
=> fix races with parallel analysis of cubins

symtabAPI/src/dwarfWalker.C
- in some instances the valid PC range for the variable was being offset twice by the base address of the shared object; the value returned by libdw already adds this offset and then dyninst adds it again in some instances
=> fix location list PC range values

parseAPI/h/GraphAdapter.h, stackwalk/h/local_var.h
stackwalk/h/local_var.h and parseAPI/h/GraphAdapter.h were incorrectly removed by d42b65910.
Fixes #1300
=> Fix public header deletes

cmake/Modules/FindLibDebuginfod.cmake
Debian distributions put the elfutils includes under <prefix>/include/elfutils. This just adds the <includedir>/elfutils subdirectory to the search where <includedir> is returned from pkg-config.
=> Search 'elfutils' subdirectory for libdebuginfod/includedir

dyninstAPI/src/BPatch_module.C
'isValid' checks that 'mod' is not null. The code here only runs if mod _is_ null. Oddly, this only showed up as a compile warning when ENABLE_STATIC_BUILDS=ON.
=> Fix possible null pointer access in BPatch_module::findFunctionByAddress

instructionAPI/h/Result.h
=> Fix incorrect format string in Result.h for u48 / s48 / u64 / s64

instructionAPI/src/Operand.C
I believe this is a misuse of snprintf format string.
Instead of outputting the numeric value in hex, it would output the value as dec followed by a literal x which makes no sense at all.
=> Manually add hex prefix when formatting an Operand

dynC_API/CMakeLists.txt
dynC is a pure C library, so it doesn't use Boost.
=> Directly link to common in dynC_API

symtabAPI/src/dwarfWalker.h
This makes it consistent with other uses of the parallel data structures.
=> Use dyn_c_hash_map in DwarfWalker

common/h/concurrent.h, symtabAPI/src/dwarfWalker.h
When OneAPI was released in 2021, the tbb:hash_compare interface was completely changed. I could not find any record of this in their release notes. This change supports both interfaces.
NB: This change does **not** add CMake support for finding TBB versions >= 2021.1.
Fixes #1306 #1304
=> Support hash_compare concept from TBB >= 2021.1

parseAPI/src/Parser.C
Don't consider a branch that is a self-loop as a potential tail call. 
Note: This commit avoids having function finalization never reach a fixed point for the bad parse of function PMPI_Accumulate in  libmpi_nvidia.so.12.0.0. However, this does nothing to fix the underlying parsing problems that led to the anomaly:
` 0x116d954 <PMPI_Accumulate+106900>:  jmp    0x116d954 <PMPI_Accumulate+106900>
`
which according to objdump should have been:
```
0x116d951 <PMPI_Accumulate+106897>:  callq  0x2a270 <MPIR_Err_create_code@plt>
0x116d956 <PMPI_Accumulate+106902>:  mov    %eax,%edi
```
Note that 0x116d954 is in the middle of the instruction at 0x116d951 reported by objdump.
@kupsch
=> ParseAPI: improve tail call recognition

instructionAPI/h/Instruction.h, instructionAPI/src/Instruction.C
* Allow the Instruction class to allow correct assignment semantics by changing a member from a reference to a pointer
* The formatter member is a reference (to a singleton) that can not be changed after it is initialized.  Assignment to this member wrongly assigns to the previously bound referent singleton and wrongly slices the rhs to the ArchSpecificFormatter base class.  The base class has no data members, and since the assignment does not change the type of the object (its vtable), it appears to have no effect.  Also a default constructed Instuction object sets the formatter to the x86 formatter even if the host was not x86.
@bbiiggppiigg please test that this fixes your use case. Test suite shows no regressions on x86_64 and arm.
fixes #1312
=> fix Instruction class to allow valid assignment

cmake/warnings.cmake
Oddly, these also show up when ENABLE_STATIC_LIBS=OFF and USE_OpenMP=ON.
Fixes #1231
=> Ignore unknown pragma warnings when building without OpenMP

elf/src/Elf_X.C
This is an error when DYNINST_WARNINGS_AS_ERRORS=ON and ENABLE_DEBUGINFOD=ON.
=> Fix shadowing of 'filename' member in Elf_X::findDebugFile

CMakeLists.txt, common/CMakeLists.txt, parseAPI/CMakeLists.txt, parseThat/CMakeLists.txt, symtabAPI/CMakeLists.txt
This also provides a dummy target so we don't have to do any additional checking when USE_OpenMP=OFF. We only use OpenMP_CXX, so I didn't create a target for the other languages (C,Fortran).
=> Use OpenMP target

dyninstAPI/src/unix.C, symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
instead of making multiple redundant copies of it. Copying and making a map out of the table incurs a significant overhead when the symbol table is large.
This significantly speeds up omnitrace when using `--caller-include` (https://github.com/AMDResearch/omnitrace/pull/202, it makes use of the `caller` method on call points.)
=> Lookup functions in the binding table directly

dataflowAPI/src/AbslocInterface.C
- add missing #include <deque>
On more platforms and library combinations <deque> is included via some other header, but there is combination where this is not true
=> add missing include file

common/src/Types.h, common/src/arch-x86.h
The platform macro guards (e.g., `os_windows`) are causing issues in the CMake refactor. The simplest solution is to fix the root cause here. Moreover, the custom fixed-size types are unnecessary since we require C++11.
=> Refactor common/src/Types.h

dyninstAPI/src/BPatch_snippet.C
`lOperand.ast_wrapper->getType()` is checked on line 189 after it's accessed on line 186.
=> BPatch_snippet::generateArrayRef - fix possible null pointer access

symtabAPI/src/Object.C, symtabAPI/src/Object.h
This was only used by the STABs parsing code. It should have been removed by 5e142eff. Language detection is handled by `void Object::getModuleLanguageInfo` and requires DWARF (it does nothing on non-ELF binaries).
=> Remove AObject::pickLanguage

symtabAPI/src/Object-elf.C
This adds C++14, Fortran03, and Fortran08 language detection. I found this while debugging a DWARF issue.
=> Update detection of DWARF languages

common/src/arch-x86.C
The vex encoded form of VPAND takes three operands dest,src1,src2.
Fixes: #1363
=> Fix sema type for vex2 encoded vpand

dyninstAPI/src/mapped_object.C
- checking `std::string::c_str() == 0` is pointless because `std::string` cannot be constructed from a `nullptr`
- C++11 standard, sect. 21.4.2.9
- Replaced with `std::string::empty()`
- add `nullptr` checks in `find.*Vector.*` functions
- Fixes issues noted here: https://github.com/AMDResearch/omnitrace/pull/235#issuecomment-1414264630
=> Fixed nullptr issues in dyninstAPI/src/mapped_object.C

common/h/entryIDs.h, common/src/arch-x86.C, instructionAPI/src/InstructionDecoder-x86.C
Add support for endbr64 and endbr32 instructions, so they are parsed correctly instead of as nop instructions.
Fixes #1327.
=> handle ENDBR64

instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.C, instructionAPI/src/AMDGPU/vega/InstructionDecoder-amdgpu-vega.C
As title, remove the use of cout in the AMDGPU instruction decoders.
Debug information should be controlled by the debug_printfs, which is still missing for instructionAPI.
=> Remove use of couts in the AMDGPU instruction decoders

common/src/arch-x86.C, common/src/arch-x86.h, instructionAPI/h/Result.h
Intel 8 bit immediate values are signed.   They were being interpreted
as unsigned on power and arm due to char differences.   This PR
ensures 8 bit values related to x86 are interpreted correctly on other
systems.   This resolves issue #1372 which the Rice group had with
incorrect CFG interpretation cross-arch.   As well as other problems
such as normal immediate values being interpreted incorrectly.
=> Insure intel 8 bit immediate values are interpreted correctly on other systems.

instructionAPI/src/Instruction.C
Both amdgpu setpc and swappc instructions are _not_ fall-through
branch instructions.  We need to stop analysis at that instruction.
The CDNA2 (MI200) instructions of swappc and setpc were missing. 
They have been added for similar fall-through prevention on that architecture.
This PR Resolves #1375
=> Prevent fall-through analysis of amd gpu swap/set pc instructions.

dataflowAPI/src/SymEval.C
Dyninst can generate a CFG just based on instructions and decoding.
However, up to this point if a semantics package was not available
for an architecture, a non-semantics architecture would result in a panic.
With this change, a warning message, similar to the crash message, 
is output once to allow users to know that they aren't using semantic 
info, and relying only on instruction decoding.
Fixes #1377
=> Allow CFG analysis based on instructionAPI alone w/out semantics.

instructionAPI/src/InstructionDecoder-aarch64.h
std::array is used in this file, but not included explicitly as on many systems this header is implicitly included recursively via another included file.  On new versions of headers this may no longer be the case, so explicitly include it.
I have not been able to reproduce this, but this seems to be the fix from the user provide issue.
Fixes #1378
=> explicitly include missing <array>

parseAPI/h/CodeSource.h, parseAPI/src/SymtabCodeSource.C
This just makes it slightly easier to pass in an `std::string` to the constructor, allowing `my_str.c_str()` directly, without needing to do a const cast or copy the string.
=> Make SymtabCodeSource take a const param

dyninstAPI/src/linux.C
- the main issue was `/sbin/ldconfig -p` on Ubuntu 22.04 has an extra line at the end: "Cache generated by: ldconfig (Ubuntu GLIBC 2.35-0ubuntu3) stable release version 2.35"
- this would result in an occasionaly segfault
- refactored the rest to avoid `strtok` (which is known to have a fair amount of problems) and consistently apply checking whether path exists
```console
$ /sbin/ldconfig -p
89 libs found in cache `/etc/ld.so.cache'
libzstd.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libzstd.so.1
libz.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz.so.1
...
ld-linux-x86-64.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
```
```console
$ /sbin/ldconfig -p
89 libs found in cache `/etc/ld.so.cache'
libzstd.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libzstd.so.1 …
```
=> Fix BinaryEdit::getResolvedLibraryPath for Ubuntu 22.04

common/h/concurrent.h
Fixes warning produced by gcc 12: a non-default allocator for tbb::concurrent_hash_map causes a new/delete mismatch warning (that appears to be a false positive).  Warning produced since tbb headers are not marked as a system headers yet. 
In the future the allocator should be changed to use the tbb scalable allocator.
Related to #1331
=> use default allocator for tbb::concurrent_hash_map

instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.C, instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.h, instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.C, instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.h
makeRegisterExpression in the derived class had
an incorrect function signature, which made
compilation fails on gcc-6 and clang.
Fix #1388
=> Fix ambiguous override of InstructionDecoder_amdgpu_*::makeRegisterExpression

dyninstAPI/src/BPatch.C
The Type class doesn't have a user-defined copy constructor and its implicit declaration is deprecated in C++20. Rearranging the construction here removes the possibility of copying.
=> Avoid possible copy in BPatch::createEnum

dyninstAPI/src/inst-aarch64.C
The special purpose registers are pushed onto the stack by
EmitterAARCH64SaveRegs::saveSPRegisters. This patch reverses the order
used for popping the stored registers from the stack. Without
this patch, some of the state registers get swapped.
=> Aarch64: Fix restoring special purpose registers order

dyninstAPI/src/inst-power.C
This is the same fix as for aarch64 (https://github.com/dyninst/dyninst/pull/1000), but for PowerPC. x86 does not have this issue.
=> Restore PPC special-purpose registers in opposite order of saving them

symtabAPI/src/dwarfWalker.C
@jmellorcrummey @mwkrentel This should suppress all of the error messages you were seeing. You can enable them by setting DYNINST_DEBUG_DWARF=1 in your environment.
=> Replace 'cerr' with 'dwarf_print' in DwarfWalker::decodeLocationList

dyninstAPI/src/codegen-aarch64.C, dyninstAPI/src/codegen-aarch64.h, dyninstAPI/src/emit-aarch64.C, dyninstAPI/src/inst-aarch64.C
The function template has a separate declaration and "definition" AND is called from translation units where neither is located. This only happens to work correctly when the TUs are linked in a specific order.
=> Fix link bug in insnCodeGen::loadImmIntoReg on aarch64

instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.h, instructionAPI/src/AMDGPU/gfx90a/InstructionDecoder-amdgpu-gfx90a.h
clang complains:
'constexpr' non-static member function will not be implicitly 'const'
in C++14; add 'const' to avoid a change in behavior [-Werror,-Wconstexpr-not-const]
=> Make InstructionAPI::isArrayIndexValid const

cmake/DyninstWarnings.cmake
When compiling with clang 15 and 16 allow a 40000 stack frame size.  clang 14 already had an exception to allow 40000.
Fixes #1417.
=> warning fix:  stack frame size

.github/workflows/spack-build.yaml
Dyninst now requires TBB >= 2019.9.
=> Github CI: use default TBB when doing spack build

.github/workflows/compiler-multibuild.yaml
This should have been included in #1415.
=> Github CI: make compiler multi-build a cron job

.github/workflows/dev-containers.yaml, .github/workflows/pr-tests.yaml
Github only allows one CPU core per job, but any number of threads. Testing shows that N=2 threads reduces build time by 2-2.5x, N=3 by 2.2x, and N=4 increases build time.
=> Github CI: increase number of build jobs

common/src/dthread.h
This makes it consistent with std::condition_variable.
Found using cppcheck:
common/src/dthread.h:114:4: warning: Class 'CondVar' does not have a copy constructor which is recommended since it has dynamic memory/resource allocation(s). [noCopyConstructor]
mutex = new mutex_t;
^
common/src/dthread.h:114:4: warning: Class 'CondVar' does not have a operator= which is recommended since it has dynamic memory/resource allocation(s). [noOperatorEq]
mutex = new mutex_t;
=> Make CondVar non-copyable, non-moveable

common/src/addrtranslate-sysv.C
Found using cppcheck:
common/src/addrtranslate-sysv.C:1046:58: error: Resource leak: fd [resourceLeak]
if (read(fd, &e_hdr, sizeof(e_hdr)) != sizeof(e_hdr)) return base;
^
common/src/addrtranslate-sysv.C:1048:28: error: Resource leak: fd [resourceLeak]
if (e_hdr.e_phoff == 0) return base;
=> AddressTranslateSysV::adjustForAddrSpaceWrap: Fix C file descriptor leak

common/src/NodeIterator.h, common/src/addrtranslate-win.C, instructionAPI/src/InstructionDecoder-x86.C, parseAPI/src/CFGFactory.C, proccontrol/src/freebsd.C
Not technically bugs, but it's better to be explicit to remove any ambiguity. Found using cppcheck's virtualCallInConstructor.
=> Remove virtual calls in constructor/destructor

common/src/Edge.C, common/src/Node.C
These were found by cppcheck:
common/src/Node.C:198:29: warning: 'operator=' should check for assignment to self to avoid problems with dynamic memory. [operatorEqToSelf]
NodeIterator &NodeIterator::operator=(const NodeIterator &rhs) {
^
common/src/Edge.C:108:29: warning: 'operator=' should check for assignment to self to avoid problems with dynamic memory. [operatorEqToSelf]
EdgeIterator &EdgeIterator::operator=(const EdgeIterator &rhs) {
=> Protect against self-assignment in copy constructors

common/h/IBSTree.h, dataflowAPI/rose/SgAsmExpression.h, dataflowAPI/rose/SgAsmPowerpcInstruction.h, dataflowAPI/rose/util/PoolAllocator.h, dwarf/h/dwarfResult.h, dynC_API/h/snippetGen.h, dyninstAPI/h/BPatch_type.h, dyninstAPI/h/StackMod.h, dyninstAPI/src/Relocation/Widgets/RelDataWidget.h, dyninstAPI/src/StackMod/StackLocation.h, dyninstAPI/src/ast.h, dyninstAPI/src/image.h, dyninstAPI/src/inst-x86.h, dyninstAPI/src/mapped_object.h, dyninstAPI/src/registerSpace.h, dyninstAPI/src/syscallNotification.h, elf/h/Elf_X.h, instructionAPI/h/Ternary.h, instructionAPI/src/InstructionDecoder-aarch64.h, parseAPI/src/BoundFactData.h, parseAPI/src/ParserDetails.h, parseAPI/src/ProbabilisticParser.h, patchAPI/h/AddrSpace.h, patchAPI/h/Point.h, symtabAPI/h/Symtab.h, symtabAPI/src/Object-nt.C, symtabAPI/src/emitElf.h
These were detected by cppcheck's uninitMemberVar*. No attempt was made to be consistent in solving each item. Some are directly initialized in the class declaration, others have modified constructor initializer lists.
@kupsch I'll take a careful look over these once the CI runs to see if there are any enum members that should have better defaults.
=> Fix uninitialized member variables

dyninstAPI_RT/src/RTfreebsd.c, proccontrol/src/process.C, symtabAPI/src/Object-elf.C
These were found using cppcheck's uninitvar and eraseDereference.
For the usages of iterator-like classes in process.C, they aren't strictly uninitialized variable usages since the classes in question are standard layout types. It would be better to replace the usages there with list construction to avoid the static check altogether.
=> Prevent use of possibly-uninitialized local variables

dyninstAPI/src/parse-power.C, dyninstAPI/src/unix.C, proccontrol/src/irpc.C, proccontrol/src/memcache.C, symtabAPI/src/Symtab-edit.C
These were all found using cppcheck.
=> Fix several resource leaks

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
There are several reasons for this.
1. It doesn't copy every member of the class
2. IBSTree doesn't have a copy constructor
3. mod_lookup_ and func_lookup_ are not copied, but are recreated in other member functions (e.g., mod_lookup()). This completely breaks the semantics of a copy ctor.
4. Resets _ref_cnt to 1
=> Remove Symtab copy constructor

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
The definition was commented out in 3709ead48 in 2009.
=> Remove Symtab::checkPPC64DescriptorSymbols

symtabAPI/h/Symtab.h
Because there is a user-defined destructor, the compiler will not generate the special member functions (e.g., copy assignment operator). However, we explicitly delete them here to signal that this class is not copyable or movable.  The destructor is also moved to the top of the class to be next to the other special member functions.
=> Explicitly delete unusable special member functions in Symtab

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
This fixes several bugs and makes the constructors now behave all the same.
=> Clean up Symtab constructors

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab-lookup.C
This fix does not address the thread safety issues in Symtab::parseFunctionRanges. That function is still thread unsafe and will require separate modifications.
@jmellorcrummey @mwkrentel This should allow you to remove the need to explicitly call `parseFunctionRanges` before calling `findModuleByOffset`. It does not fix #1446. That will be a separate PR.
=> Make Symtab::getContainingInlinedFunction lazy parsing threadsafe

symtabAPI/h/Function.h, symtabAPI/h/Symtab.h, symtabAPI/h/Variable.h, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C
The IBSTree type is threadsafe, but the lazy initialization of them is not. Generally, we don't expect users to use these directly in a multithreaded context (e.g., via `mod_lookup()`). However, it is possible for users to indirectly access them through `getContainingInlinedFunction` or `findModuleByOffset`. At this time, an empty `IBSTree` occupies about 300 bytes of the total ~8.5kB of a `Symtab` object.
This works toward fixing #1446.
=> Remove lazy initialization of IBSTrees in Symtab

symtabAPI/src/Object-elf.C
According to the llvm page
https://llvm.org/docs/AMDGPUUsage.html#relocation-records AMDGPU backend generates Elf64_Rela records.
This fix added the case for EM_AMDGPU to
static Region::RegionType getRelTypeByElfMachine
such that it uses RELA instead of the default REL type.
=> Fix EM_AMDGPU to use RELA as Region Type

symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h
It's usage was removed by 4be991a7 in 2021.
I just happened to notice this while doing some call tree tracing.
=> Remove Object::dwarf_parse_aranges

common/h/entryIDs.h, common/src/arch-x86.C, dataflowAPI/src/convertOpcodes.C
These were found when comparing against Capstone. There are a few breakages in here. For example, 1dcab37d renames `e_cmpsd_sse` to `e_cmpsd`, consistent with the rest of the SEE opcodes.
=> Fix x86 misspelled, incorrect, and invalid opcodes

instructionAPI/h/Instruction.h, instructionAPI/src/Instruction.C, instructionAPI/src/InstructionDecoder-x86.C
The ret instruction formats incorrectly with an operand of '(%rsp)'.  The operand should have been flagged as implicit so it is not included in the output.
- eliminate all but one overloaded Instruction::appendOperand` using default parameters
- add isImplicit parameter defaulting to false to Instruction::addSuccessor
- add isImplicit to the ret instruction's addSuccessor call to set the ret_addr (which adds the operand to the Instruction object)
Fixes #1458
=> fix x86_64 ret instruction formatting

instructionAPI/src/ArchSpecificFormatters.C, instructionAPI/src/Operand.C
This fixes three issues when formatting an x86_64 instruction or its operands:
1) Fix the order of operands when formatting the instruction to be the
AT&T syntax order.  If the instruction had three or more operands.
Conversion from the internal (Intel) order rotated right by 1 instead
of reversing the operands.
Fixes #1459
2) Eliminate special treatment of register %kN as the first operand as
mask registers in Instruction::format as Operand::format already
formats these as masks (enclosed in braces) and not all uses of mask
registers are as a mask.
Fixes #1461
3) Fix Operand::format to produce the correct disassembly operand
string.  The formatting of the internal Expression needs to be done
for some indirect values.  This was done in the Instruction::format
instead of directly in …
=> improve intel instruction & operand formatting

instructionAPI/h/ArchSpecificFormatters.h, instructionAPI/src/ArchSpecificFormatters.C
- pass string and vector parameters by const reference instead of by value for performance
- add ArchSpecificFormatter::getInstructionString and remove the overridden versions in the non-x86_64 as they were functionally the same, but not identically written
- remove virtual and add override to overridden methods
=> modernize ArchSpecificFormatter classes

instructionAPI/h/ArchSpecificFormatters.h, instructionAPI/h/Instruction.h, instructionAPI/src/ArchSpecificFormatters.C, instructionAPI/src/Instruction.C
Add method Instruction::getDisplayOrderedOperands to return the operands that are displayed (non implicit operands) when formatting an instruction for disassembly.  Returns a vector of Operands in display order.
These operands can be inspected and formatted to produce a disassembly string with annotations.
=> add getDisplayOrderedOperands interface

instructionAPI/h/Instruction.h
- do not export since it is now private, and should not have been used
externally (comment said it was to work around old compiler issue).
- cleanup method order and remove comment
Suggested in https://github.com/dyninst/dyninst/pull/1457#discussion_r1273826614
=> do not export Instruction::appendOperand

dwarf/src/dwarfHandle.C, elf/h/Elf_X.h, elf/src/Elf_X.C
Add minimal support to parse Intel's new ZeBinaries.
It's unclear at this time how we should treat Intel's XE Gen12/Tiger Lake binaries, so we just treat them as Gen9 (Ponte Vecchio) for now.
=> add support for EM_INTELGT

instructionAPI/src/Instruction.C
This was originally part of #638.
=> Do not decode operands for invalid opcodes

symtabAPI/src/emitElf.C
This is triggered when a binary with no .rel.dyn and .rela.dyn sections, but its target platform uses rel type relocation records. This happened on an AMDGPU binary that was previously incorrectly specified as using a rel relocation record.
Fixes #1445
=> Fix hang when creating ELF dynamic sections

instructionAPI/h/ArchSpecificFormatters.h, instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.C, instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.h, instructionAPI/src/AMDGPU/gfx90a/InstructionDecoder-amdgpu-gfx90a.C, instructionAPI/src/AMDGPU/gfx90a/InstructionDecoder-amdgpu-gfx90a.h, instructionAPI/src/ArchSpecificFormatters.C, instructionAPI/src/Register.C
Fix missing parameter for makeRegisterExpression
During one of the PRs that targets compiler warning,
the num_elements parameter to makeRegisterExpression is omitted,
resulting in all register operands are displayed separately,
whether they should be displayed as a group or not.
In addition to adding the parameter, certern unused helper functions
and fields of InstructionDecoder-amdgpu-gfx*** has been removed
to avoid shadowing of variable names.
(Note that this change isn't applied to vega as we don't have ISA-XML for it.)
Also, the logic for handling this type of formatting is extracted out of Register.C
into a helper function in ArchitectureSpecificFormatter.C
=> Fix AMDGPU register formatting

symtabAPI/src/dwarfWalker.h
Including anything in <bits/*> is not portable. Also, the contents of this header were never used.
Stan Cox (scox@redhat.com) reported:
It's not included as the first thing in the file, which means it can't use the precompiled version of that header
(https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html) and therefore it's just including the entire C++ standard library, which is going to be much slower than just including the right headers.
@stanfordcox
=> Don't include compiler-specific headers

symtabAPI/h/Symtab.h
It was added by 1867619517b3 in 2015, but was never implemented.
=> Remove Symtab::forceFullLineInfoParse

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
Its usage was removed by cabbe58ff in 2015. It's a private function, so there are no API/ABI issues in removing it.
=> Remove Symtab::updateIndices

symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h
Its definition was removed by 758aa226 in 2016.
=> Remove declaration of Object::load_shared_object

dyninstAPI/src/image.h
It's definition was removed by 6c65e3c9a in 2007.
=> Remove declaration of image::getModuleLanguageInfo

symtabAPI/h/Module.h, symtabAPI/src/Module.C
This is never called internally. The filename corresponding to the module is a class invariant. It makes no sense to make it mutable. This member function is not documented.
=> Remove Module::setName

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
There are many places where this is called without a user realizing it. If they were to call any of those functions in parallel, type parsing would break.
=> Make Symtab::parseTypesNow thread-safe

symtabAPI/src/Object-elf.C, symtabAPI/src/parseDwarf.C
Its usage was removed by 340799a in 2017.
=> Remove pd_dwarf_handler

symtabAPI/src/dwarfWalker.C
These should have been part of 71f2e14d3.
=> Use uniform CU checks in DwarfWalker

symtabAPI/h/Module.h, symtabAPI/src/Module.C, symtabAPI/src/Symtab.C
A Module shouldn't modify the Symtab object to which it belongs. It knows what ranges belong to it (see
Object::fix_global_symbol_modules_static_dwarf), so it can munge them into a collection of `ModRange`s.
The `ranges_finalized` member was never needed as the only place it was set was in `finalizeRanges` which is the only place where `ranges` was emptied.
=> Fix responsibility inversion in Module::finalizeRanges

symtabAPI/doc/API/Symtab/Function.tex, symtabAPI/doc/API/Symtab/FunctionBase.tex, symtabAPI/h/Function.h
This is never called from within Dyninst and should never be called by a user.
=> Remove FunctionBase::setReturnType(Type*)

symtabAPI/src/dwarfWalker.C
Since 8b400af5, functions are guaranteed to only be parsed once, so the return type can never be set before the call here. Checking the return type circularly invokes Symtab::parseTypesNow which deadlocks since 7f1e24d.
=> Don't check for existing return type when parsing DWARF subprogram

dwarf/h/dwarf_cu_info.hpp
If a DIE is a CU, then it contains a reference to its Dwarf_CU.
Introduced by 71f2e14d3 (PR1499).
=> Fix inverted logic  in DwarfDyninst::is_cudie

symtabAPI/src/dwarfWalker.C
From 2.6.4.16 of the DWARF5 standard
Prior to DWARF Version 5, the current compilation file name was not
represented in the file_names field. In DWARF Version 5, the current
compilation file name is explicitly present and has index 0. This is
needed to support the common practice of stripping all but the line
number sections (.debug_line and .debug_line_str) from an executable.
However, libdw takes care of this in `dwarf_getsrcfiles`.
Fixes a major bug where we produce no function parameter information
when there is only one CU in a binary because
DwarfWalker::parseFormalParam requires line information.
Fixes #1156
=> Parse all DWARF source files in DwarfWalker::buildSrcFiles

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
It was added by 49df4377c in 2012, but never used.
=> Remove DwarfWalker::version member variable

dwarf/h/dwarf_names.h
For C++ member functions, compilers will sometimes add a DW_AT_name called 'this', and we don't want to mangle that.
=> Don't create a name for artificial DIEs with a DW_AT_name

dataflowAPI/src/Visitors.C, parseAPI/src/SymbolicExpression.C
Fix implementation in dataflowAPI to have end_bit exclusive.
Fix implementation in parseAPI to be based on begin_bit and end_bit instead of based on size only.
Fix #1510.
=> Fix Implementation for RoseOperation::extractOp

parseAPI/src/SymbolicExpression.C
- set integer bit size of equalsizeOp to be 1
- set integer bit size of andOp to be max size of operands
- set integer bit size of orOp to be max size of operands
Fix #1517
=>  Fix int size of rose operations return values

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
Its usage was removed by 4bc7f25d in 2020.
=> Remove Symtab::fixup_SymbolAddr

symtabAPI/src/Symtab.C
This makes it easier to understand what's happening. It's still not clear why the region check is necessary.
=> Refactor Symtab::addSymbolToAggregate

symtabAPI/CMakeLists.txt, symtabAPI/h/Function.h, symtabAPI/h/Symtab.h, symtabAPI/src/Symtab-edit.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C, symtabAPI/src/indexed_symbols.hpp, symtabAPI/src/symtab_impl.hpp
This allows us to more easily modify the parallelism around the big tables (e.g., `indexed_modules`) without bumping the ABI around, meaning we don't have to wait until a major release to make those changes. This also removes internal details like `concurrent.h` which puts TBB into the pubic API and the multiple Boost headers needed for `multi_index`.
Although `ModRangeLookup* mod_lookup();` was a public member, it was never documented, and should never be called by a user. I'm not considering this an API-breaking change.
=> Hide implementations of complex data structures in SymtabAPI::Symtab

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
Its usage was removed by aaa5e321c in 2017.
=> Remove dwarfWalker::getHighPCLowPC

instructionAPI/src/AMDGPU/gfx908/amdgpu_gfx908_decoder_impl.h, instructionAPI/src/AMDGPU/gfx90a/amdgpu_gfx90a_decoder_impl.h, instructionAPI/src/AMDGPU/gfx90a/amdgpu_gfx90a_insn_entry.h
Fields in instruction layouts can have implicit LSBs. 
Previously this wasn't taken into consideration,
and causes overflow and decoding instruction.
This PR fixes the layout definition to include the LSBs.
=> Fix overflow of fields in instruction layout

symtabAPI/src/Object-elf.C
A minor cleanup item, but it makes IDE lookup easier.
=> Use fully-qualified name in fix_global_symbol_modules_static_dwarf

symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C, symtabAPI/src/symtab_impl.hpp
This simplifies the handling of modules and ensures a default always exists. Creation must happen after the MappedFile has been created (`Symtab::file()` checks that one has been created), but before the symbols are assigned to a Module.
=> Make a default module a class invariant in Symtab

symtabAPI/h/Function.h
This was detected by -Winconsistent-missing-override enabled by default in clang-15.
=> Mark SymtabAPI::Function::removeSymbol as 'override'

dyninstAPI/src/image.C, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C
- Add findModuleByOffset(Offset)
- Deprecate findModuleByOffset(Module *&, Offset)
It is replaced by findModuleByOffset(Offset).
- Remove findModuleByOffset(std::set<Module *>&, Offset)
It was never documented and makes no sense as offsets are unique
within a module (i.e., DWARF CU). Dyninst uses a separate
Symtab instance for each object file in an archive, as well.
=> Add new Symtab interface for accessing modules by offset

symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
The Module into which the line information will be isnserted cannot be uniquely identified by name.
=> Remove public Symtab API for adding line information

common/h/compiler_annotations.h
- Added the macro DYNINST_DEPRECATED(msg). It can be placed before a function, method, type or variable so that on use a deprecated diagnostic is produced.  The macro works using language standard annotation or compiler specific annotations or has no effect if neither is available.
=> add deprecated annotation support

symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Symtab-lookup.C
This will eventually replace `findModuleByName(Module *&ret, const std::string name)`.
=> Add findModulesByName(std::string const&)

common/h/compiler_annotations.h
The clang compiler allows the use of some attributes introduced in a later language standard than use to compile the source as a non-standard extension.  Clang's __has_cpp_attribute and __has_c_attribute returns true for these attributes.  If one of these attributes is used, clang warns of a non-standard language feature usage.  So for clang, only use a standard attribute if the feature test returns true and the language standard version is valid.
- fix clang's [[deprecated]] (only if C++ >= 14 and C >= 23)
- use now known C-23 __STDC_VERSION__ value 202311L
=> fix deprecated annotation warning using clang

dwarf/CMakeLists.txt, dwarf/h/dwarf_cu_info.h, dwarf/h/dwarf_names.h, dwarf/h/dwarf_unit_info.h
This also refactors the unit type checks out of dwarf_cu_info.h into dwarf_unit_info.h.
This fixes the crashes found by @bigtrak on Fedora. The root cause there is that their system libraries are assembled as a collection of DW_TAG_partial_units instead of DW_TAG_compilation_units. This is likely due to them using split and compressed DWARF (at least its a recommended idiom for that case).
=> Create unique name for unnamed partial DWARF DIEs

.github/workflows/dev-containers.yaml, .github/workflows/pr-tests.yaml, docker/Dockerfile.fedora
This uses gcc-13. Clang won't work because the only available libomp is for clang-17, but the highest installable version of clang is 15.
=> GithubCI: add testing on Fedora-39

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
It's replaced with the updated Symtab::findModuleByOffset. Finding by name was always unnecessary as we know the offset of the current DIE.
This is a step toward removing the broken Symtab::findModuleByName.
=> Remove DwarfWalker::setModuleFromName

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab-edit.C
It is never used. Not a breaking change as it's private.
I have left the function of the same name in Aggregate because it's protected, there is a virtual dtor, and that class is accessible by users. It's possible that someone is using it.
=> Remove Symtab::changeSymbolOffset

symtabAPI/doc/API/Symtab/Module.tex, symtabAPI/h/Module.h
This was added by c848409 in 2009, but never implemented. It looks like this was copy/pasted from the earliest Symtab rewrite.
=> Remove Module::findFunctionsByName

symtabAPI/doc/API/Symtab/Module.tex, symtabAPI/h/Module.h
This was added by c848409ec in 2009, but never implemented. It looks like this was copy/pasted from the earliest Symtab rewrite.
=> Remove Module::findFunctionByEntryOffset

symtabAPI/doc/3-Examples.tex, symtabAPI/doc/API/LineInfo/Iterating.tex, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C
This can't be merged until after https://github.com/dyninst/examples/pull/40.
A Symtab::Module is a one-to-one mapping to a DWARF compilation unit
(CU). In DWARF4, we consider a CU to be an entry in the .debug_info
section with the tag DW_TAG_compile_unit. In DWARF5, we also include
entries with the tag DW_TAG_partial_unit as they can contain symbol
definitions; we assume libdw will merge all other split unit types for
us.
The name of a module is the DW_AT_name of the containing DIE. This is
either the full path name of the source file used to create the CU or
the relative path of the same with respect to the DW_AT_comp_dir. We
ensure that the module's name is always an absolute path.
Modules have never been required to have unique names. That is, many
modules can share the same name. The …
=> Remove Symtab::findModuleByName(Module *&, std::string)

common/h/compiler_annotations.h
- gcc 6's __has_c_attribute and __has_cpp_attribute return true if an attribute is supported as a non-standard extension, but if used produces a warning if the language standard is earlier than the attribute's standardization; treat gcc 6 like clang and only allow if the language standard is after the introduction.
- refactor the conditional compilation tests into common macros
=> fix gcc 6's broken __has_x_attribute

dyninstAPI/src/image.C, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C, symtabAPI/src/symtab_impl.hpp
Returns the module with PC ranges that contain a given offset (really address). By contrast, findModuleByOffset(Offset) finds a module starting at the given offset.
This is the correct replacement for `Symtab::findModuleByOffset(std::set<Module *>&, Offset)` removed in #1545.
=> Add Symtab::getContainingModule(Offset)

symtabAPI/src/Symtab.C
This should have been part of ddd2315b5.
I have no idea how these were left out of #1571. I distinctly remember fixing them.
=> Use Symtab::getContainingModule instead of Symtab::findModuleByOffset

dyninstAPI/h/BPatch_statement.h, symtabAPI/CMakeLists.txt, symtabAPI/h/LineInformation.h, symtabAPI/h/Module.h, symtabAPI/h/RangeLookup.h, symtabAPI/h/Statement.h, symtabAPI/src/Module.C, symtabAPI/src/Statement.C
This is just a mess to try and read. It also reduces the size of includes in several places.
=> Refactor symtab/Module.h

dyninstAPI/h/BPatch.h, dyninstAPI/src/BPatch.C, dyninstAPI/src/mapped_module.C, dyninstAPI/src/mapped_module.h
=> Deprecate mapped_module::truncateLineFilenames

symtabAPI/h/Module.h, symtabAPI/src/Module.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.h
There is no need to store the CU DIE from which a Module instance is
derived. The address of the CU can be used to reconstitute the
entry in the .debug_info section using dwarf_addrdie.
Because Module.h is part of the public API for Dyninst, this also
removes the transitive dependency on libdw.
=> Remove DWARFisms from Symtab::Module

symtabAPI/h/Module.h
This is never used and Module doesn't inherit from AnnotatableSparse.
=> Remove MODULE_ANNOTATABLE_CLASS

dwarf/h/dwarf_cu_info.h, symtabAPI/src/Object-elf.C
As of libdw 0.189, `dwarf_addrdie` assumes the presence of .debug_aranges. For compilers that do not emit one, or emit an invalid one (e.g., gtpin binaries), then manually search through all of the CUs to find a match.
=> Fix line information parsing for CUs with no aranges

dyninstAPI/src/mapped_module.h
It was introduced in 2005 by 5731bd02a, but never implemented.
=> Remove mapped_module::getAddrFromLine

instructionAPI/h/Result.h
These enumerators were reordered by 85fd6745. It turns out there is an undocumented requirement that they be in this specific order. Rather than fixing the incorrect usage of inequality checks on enumerators, I'm putting them back in order with a note.
=> Reorder enumerators in instructionAPI::Result::Result_Type

dyninstAPI/src/BPatch_flowGraph.C
Its usage was removed by f531f7261 in 2011.
=> Remove BPatch_flowGraph::getLoopMinMaxSourceLines

dyninstAPI/src/codeRange.h
It was added by fa76232b4 in 2005, but never implemented.
=> Remove codeRange::operator<<

symtabAPI/h/Symtab.h
It was added by 3a7f5df6 in 2009, but never implemented.
=> Remove Symtab::getSymbolByIndex

symtabAPI/h/Symtab.h
This should have been removed by 7e62e5e7f.
=> Remove Symtab::newModule declaration

common/h/registers/MachRegister.h, common/src/registers/MachRegister.C
It makes no sense to have this and the std::string version when they do the same thing.
=> Remove MachRegister(int, char const*) overload

common/h/registers/MachRegister.h, common/src/registers/MachRegister.C
This fixes several linter issues with the switches and tidies up some dead code.
=> Clean up MachRegister class

symtabAPI/src/Symtab.C
This makes it consistent with serr.
=> Make SymtabAPI::errMsg thread_local

symtabAPI/src/Symtab-edit.C
Having a default module was made a class invariant in 9e855250.
=> Remove module containment check in Symtab::create{Function,Variable}

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
These were part of the serialization interface and should have been removed by f4ee3410b.
=> Remove Symtab::exportXML,exportBin,importBin

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C
It's never used. MappedFile is also an opaque type here, so users could never have used it. This makes it not an ABI/API-breaking change.
=> Remove Symtab(MappedFile*)

symtabAPI/h/Function.h
It was added by 5ed068167 in 2013.
=> Remove redundant declaration of SymtabAPI::FuncRangeCollection

symtabAPI/h/Function.h, symtabAPI/src/dwarfWalker.C
It's only ever used in DwarfWalker::setRanges, and that is only ever called from DwarfWalker::parseSubprogram which is now correctly guarded (as of 8b400af59b).
=> Remove FunctionBase::ranges_lock

parseAPI/src/Block.C
Found by cppcheck's nullPointerRedundantCheck.
=> Make null pointer checks for ParseAPI::Block::_obj consistent

symtabAPI/src/Object-elf.C
=> Remove locking before calls to convertDebugOffset

symtabAPI/src/Symbol.C
These were added by c848409ec in 2009, but never used.
=> Remove extraneous variables in Symbol.C

dyninstAPI/src/binaryEdit.C
The variable is used before the assert.
=> Remove useless assert in binaryEdit::writeFile

dyninstAPI/src/binaryEdit.C
The usage of the variables it protects was removed by 399a10ea in 2007.
=> Remove code protected by USE_ADDRESS_MAPS

dyninstAPI/src/ast.C, dyninstAPI/src/ast.h
The lack of consistent checking of empty pointers was fixed by #1609, but those changes broke the semantics of the class. This reverts those changes and fixes the pointer checks more directly.
=> Fix astOperatorNode semantics

symtabAPI/src/Object-elf.h
=> Explicitly mark overridden member functions in Object-elf

dyninstAPI/src/binaryEdit.C, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C
There are several problems here:
1) Users shouldn't be creating modules
2) When created, the returned module must be "fixed up" before it's
useful. There's no need for that when one could be properly constructed
at the callsite inside Dyninst.
3) It violates the Single Responsibility Principle
=> Deprecate Symtab::getOrCreateModule

dwarf/h/dwarf_cu_info.h, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
The PC value can be non-unique across CUs. For example, they can all be 0x0 for a PIE binary. The offset of the CU is unique as it's the location inside of the .debug_info table.
Fixes #1625
=> Construct a Module from the CU's offset not its PC

common/h/registers/MachRegister.h, common/src/registers/MachRegister.C
It was added by efa87d1f4d in 2010, but never documented or used.
=> Remove MachineRegister::getSubRegValue

common/h/registers/x86_64_regs.h, common/src/registers/MachRegister.C, dataflowAPI/src/SymEvalPolicy.C
The values for the RFLAGS fields VM..ID will get updated to the x86 ones after #1629 is merged.
=> Clean up and improve documentation of x86_64 registers

CMakeLists.txt
In CMake 3.27 and above the find_package(<PackageName>) command now searches prefixes specified by the upper-case <PACKAGENAME>_ROOT CMake variable and the <PACKAGENAME>_ROOT environment variable in addition to the case-preserved <PackageName>_ROOT and <PackageName>_ROOT variables used since policy CMP0074. This policy provides compatibility with projects that have not been updated to avoid using <PACKAGENAME>_ROOT variables for other purposes.
The OLD behavior for this policy is to ignore <PACKAGENAME>_ROOT variables if the original <PackageName> has lower-case characters. The NEW behavior for this policy is to use <PACKAGENAME>_ROOT variables.
=> Set new CMake policy for upper-case <NAME>_ROOT variables

dataflowAPI/src/liveness.C
There is no requirement that the two values for MMX be the same between the two architectures.
=> Fix register check in LivenessAnalyzer::isMMX

parseAPI/src/debug_parse.C
Using a per-thread file here is cumbersome. Including the thread id in the message and synchronizing vprintf makes this work for multiple threads.
=> Write to stderr in ParseAPI::parsing_printf

parseAPI/src/debug_parse.C
This trips a clang-12 ICE.
https://github.com/llvm/llvm-project/issues/49904
=> Don't use capture lambda in ParseAPI::parsing_printf_int

docker/build_base_images.sh
Should probably only do what's written on the tin.
=> Docker: only build base images in build_base_images.sh

.github/workflows/build.yaml
Should have been part of 39899e55bf.
=> Github CI: Pass '-y' to apt when removing libomp

instructionAPI/h/Operand.h
As you can see below, std::constuct_at is requiring that Operand be noexcept constructible. I _think_ this is a QoI item in libstdc++.
1. The offending call to std::vector::resize(size_type) at RoseInsnFactory.C:152 is covered by the note in (https://en.cppreference.com/w/cpp/container/vector/resize):
In overload (1), if T's move constructor is not noexcept and T is not
CopyInsertable into *this, vector will use the throwing move
constructor. If it throws, the guarantee is waived and the effects
are unspecified.
2. Operand's ctor is _not_ noexcept, but it _is_ CopyInsertable (https://en.cppreference.com/w/cpp/named_req/CopyInsertable), so we get the second part and encounter UB.
3. A note on CopyInsertable says that a CopyInsertable must use std::construct_at (see cppref page above), and …
=> Fix libstdc++ c++20 noexcept requirement for Operand ctor

cmake/DyninstWarnings.cmake
Debug builds with clang-13 now have stack frame consumption of 37512 bytes. I think this is due to upstream patch version bumps in Ubuntu.
=> Suppress -Wframe-larger-than in power_opcode_table in clang-1{3,7}

.github/workflows/compiler-multibuild.yaml
gcc-12 has some STL bugs for these standards.
=> Github CI: Use gcc-13 for c++2{0,3}

.github/workflows/consumers.yaml
Building the HEAD of dynininst against the last release of HPCToolkit is a good idea for tracking breaking changes, but it ultimately produced more noise than signal. Making sure that HPCToolkit's latest source will compile with Dyninst's latest source is likely a better measure.
=> GithubCI: only build hpctoolkit@develop

.github/workflows/pr-tests.yaml
This will make re-running the failed actions cheaper.
=> GithubCI: don't fail fast for PR tests

parseAPI/h/CFG.h
Function::region() returns a pointer to CodeRegion class. Comparing pointers directly with 'less' has a lot of issues, ranging from nondeterministic order of functions in the resulting array to it not always having a well defined behavior according to standards.
Here I tried to recreate what I believe was the intended implementation of the predicate: sort based on region address first, function address second.
=> Use code region boundaries for ParseAPI::Function::less comparator

symtabAPI/h/Module.h
fix nullptr dereference if Module* is nullptr; print "null" instead
=> fix operator<< for Module*

parseAPI/src/IA_IAPI.C, parseAPI/src/IA_IAPI.h, parseAPI/src/IA_aarch64.C, parseAPI/src/IA_aarch64.h, parseAPI/src/IA_amdgpu.C, parseAPI/src/IA_amdgpu.h, parseAPI/src/IA_power.C, parseAPI/src/IA_power.h, parseAPI/src/IA_x86.C, parseAPI/src/IA_x86.h
This also requires those members be defined for all classes derived from IA_IAPI.
Originally part of #1670
=> Refactor IA_IAPI::isSyscall,isInterrupt into arch-specific files

cmake/DyninstLibrarySettings.cmake, cmake/DyninstOptions.cmake
Currently, all symbols are hidden by default and
then explicitly made visible. This is the behavior we want for publishing Dyninst libraries, but unit testing the internal functionality requires access to these symbols. This option allows that.
It is explicitly not described in DyninstOptions.cmake because it is not intended to be used by regular users.
=> Add CMake option to control symbol visibility

parseAPI/src/IA_IAPI.C
This was broken by e7db16f5 in 2010.
Originally part of #1670
=> Fix logic error in IA_IAPI::isInterruptOrSyscall

parseAPI/src/Parser.C
165f19cd and 091929d6 changed the parsing semantics of system calls such that software interrupts (e.g., `int` on x86) are always interpreted as system calls. The `hasCFT()` check on line 1824 now covers all of the system call cases because it considers those instructions to have a control flow target (CFT).
Its non-use was verified against /usr/libx32/libc.so.6, /usr/lib/i386-linux-gnu/libc.so.6, /usr/lib/x86_64-linux-gnu/libc.so.6, and /usr/lib32/libc.so.6 on Ubuntu 22.04.
=> Remove explicit check for system calls in parse_frame_one_iteration

dataflowAPI/h/bitArray.h
They were added by 3a70928cc in 2007, but never used.
=> Remove bitArray SPEC_*_BIT macros

parseAPI/h/CodeObject.h, parseAPI/src/CodeObject.C, parseAPI/src/Parser.C, parseAPI/src/Parser.h
Parser::parse_at takes only one target at a time. This has two repercussions:
* It can't take full advantage of parallel parsing when there are multiple targets in need of it.
* It still enters and exits OMP parallel loop. This operation has its own performance overhead that depends on the host system (number of processors and OMP configuration). This overhead can be very significant.
This change introduces Parser::parse_vec that takes a vector of targets and parses them in parallel.
When there are significant number of parse_at calls, performance gains from migrating to parse_vec can be huge. Parsing what initial parse() missed in libLLVM-12.so.1 with parse_at took nearly 20 minutes on 4-core hyper-threaded CPU. Doing the same with parse_vec took less than 4 minutes. On 128-bit ARM64 …
=> Add CodeObject::parse overloads to accept multiple targets

.github/workflows/pr-tests.yaml, .github/workflows/unit-tests.yaml
This will help with debugging test failures.
=> GithubCI: use verbose output with ctest

dataflowAPI/src/slicing.C
This check was added by 578ff24aa 2017, but the logic is inverted. From the commit message:
Currently when backward slicing, a absloc that is written by call
defined by abi will be killed, however, caller saved registers
can/should survive
It's also unclear why r11 was excluded as it's not saved across function calls (i.e., not callee-saved).
Fixes #1280
=> Do not kill caller-saved registers when slicing backward

common/h/registers/x86_64_regs.h
FLAGS and BASEA should be unique.
This was introduced by 30f08e7b in 2023.
=> Fix duplicate base ID in x86_64 GPRs

common/h/registers/MachRegister.h, common/src/registers/MachRegister.C
This makes writing ABI rules much simpler. It could also be useful for some power users.
The registers returned are in the order they are declared in common/h/registers/<arch>_regs.h.
=> MachRegister: Add interface for collecting and retrieving all registers

common/src/registers/MachRegister.C
It's defined in the wrong scope, so it's not accessible outside of MachRegister.C.
Introduced by 88ad81c14 in 2024.
=> Fix definition of MachRegister::getAllRegistersForArch

dataflowAPI/h/liveness.h
It has never worked because it doesn't dereference the output iterator.
=> Remove LivenessAnalyzer::query(ParseAPI::Location,Type,OutputIterator)

.github/workflows/system-libs.yaml
change shell code in workflow to be /bin/sh compliant instead of using bash constructs
=> fix system-lib github workflow

.github/workflows/system-libs.yaml
.hmac files are library files so do not try to parse
=> ignore .hmac files in system-libs github workflow

instructionAPI/src/AMDGPU/gfx908/appendOperands.C, instructionAPI/src/AMDGPU/gfx90a/appendOperands.C, instructionAPI/src/AMDGPU/gfx940/appendOperands.C
This commit fixes an issue with the use of dynmaic_pointer_cast in appendOperands.C, 
where the base type should be used in stead of the Ptr type.
Fixes #1725
=> Fix AMDGPU register operand expansion

.github/workflows/consumers.yaml
have spack use python that it built and intalled instead of the system python, so meson gets installed in the correct path
=> fix hpctoolkit github ci workflow

symtabAPI/src/dwarfWalker.C
This causes an unused function warning when USE_OpenMP=OFF.
We could also hide the `#prama omp declare` right after this and remove the CMake check (https://github.com/dyninst/dyninst/blob/master/cmake/DyninstWarnings.cmake#L93).
=> Hide ompc_leftmost reducer if not using OpenMP

common/src/arch-x86.C
Without checking Dyninst recognizes invalid combinations of VEX/EVEX prefixes and opcodes as valid instructions.
An example:
```
_start:
.byte 0x62, 0x61, 0x64, 0x20, 0x65, 0x78, 0x63
```
Objdump:
```
0000000000001000 <_start>:
1000:	62                   	.byte 0x62
1001:	61                   	(bad)
1002:	64 20 65 78          	and    %ah,%fs:0x78(%rbp)
```
Dyninst without this change:
```
"_start" :
1000: "pcmpgtw {k0},0x63(%rax),%mm7
```
Which is not a valid instruction. VEX/EVEX prefixed instructions can't operate on MMX registers.
The `&& false` part was introduced in 39caf8e245 and most probably is some debugging change that slipped into the main code by accident.
=> x86: check that opcode supports VEX/EVEX prefix if it is present

common/src/arch-x86.C
3DNow instructions have their opcode as one byte at the very end. It needs to be consumed when we are decoding the instruction. Dyninst doesn't really support 3DNow instruction set, but with this change we at least remain in sync with the instruction stream.
An example:
```
_start:
.byte 0xf, 0xf, 0xe2, 0x9a, 0xf, 0xf, 0xc5, 0x9a, 0xf, 0xf, 0xf2, 0x9e, 0xf, 0xf, 0xfd, 0x9e
```
Objdump:
```
0000000000001000 <_start>:
1000:	0f 0f e2 9a          	pfsub  %mm2,%mm4
1004:	0f 0f c5 9a          	pfsub  %mm5,%mm0
1008:	0f 0f f2 9e          	pfadd  %mm2,%mm6
100c:	0f 0f fd 9e          	pfadd  %mm5,%mm7
```
Dyninst without this change:
```
"_start" :
1000: "[FIXME: GENERIC 3DNow INSN] %mm2,%mm4
```
Dyninst with this change:
```
"_start" :
1000: "[FIXME: GENERIC 3DNow INSN] %mm2,%mm4"
1004: "[FIXME: …
```
=> x86: correctly detect 3DNow instruction length

instructionAPI/src/Operation.C
The only instruction supported by Dyninst that references flag RF is RSM. An attempt to getReadSet or getWriteSet for it fails an assertion.
Sample code:
```
_start:
rsm
```
Dyninst without change:
```
ERROR: unhandled entry x86::rf
code_sample: /home/batuzovk/projects/dyninst-upstream/instructionAPI/src/Operation.C:541: Dyninst::InstructionAPI::Operation::SetUpNonOperandData()::<lambda()>: Assertion `0' failed.
Aborted
```
=> x86: handle flag RF

common/src/arch-x86.C
Currently Dyninst allows all group map opcodes to have VEX prefix, which is not correct.
An example:
```
_start:
.byte 0x62, 0x61, 0x6c, 0x29, 0x0, 0x6f, 0x75
```
Objdump:
```
0000000000001000 <_start>:
1000:	62 61 6c 29 00       	(bad)
1005:	6f                   	outsl  %ds:(%rsi),(%dx)
1006:	75                   	.byte 0x75
```
Dyninst without this change:
```
"_start" :
1000: "verw {k1},0x75(%rdi)"
```
Instruction `verw` doesn't support VEX or EVEX prefixes.
This change requires #1746 to have an actual effect.
=> x86: only group opcodes from groupMap2 can be VEX-prefixed

common/src/arch-x86.C
Support decoding of XOP instructions from multiply-and-accumulate group. They were partially supported before. There were IDs for them and one variant was present in decoding tables.
Code sample for testing purposes:
```
_start:
vpmacsdd %xmm5, %xmm3, %xmm4, %xmm1
vpmacsdd %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacsdqh %xmm5, %xmm3, %xmm4, %xmm1
vpmacsdqh %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacsdql %xmm5, %xmm3, %xmm4, %xmm1
vpmacsdql %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacssdd %xmm5, %xmm3, %xmm4, %xmm1
vpmacssdd %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacssdqh %xmm5, %xmm3, %xmm4, %xmm1
vpmacssdqh %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacssdql %xmm5, %xmm3, %xmm4, %xmm1
vpmacssdql %xmm5, 0x123(%rbx,%rcx,4), %xmm4, %xmm1
vpmacsswd %xmm5, %xmm3, %xmm4, %xmm1
vpmacsswd …
```
=> x86: support XOP multiply-accumulate instructions

symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h
This patch addresses a race condition that occurs when parsing an NVIDIA binary where two modules point to the same object. The NVIDIA binary where the race condition was initially discovered is included in this pull request.
The issue arises when multiple threads attempt to open the object and parse the line map concurrently. This fix ensures proper handling for this specific use case, mitigating the lower-level race condition. However, it is important to note that a potential race condition exists at a higher level.
If two threads call parse on the same module, a race condition occurs as both threads attempt to set the line information for the module. Currently, there is no mechanism to ensure mutual exclusion in this scenario.
This patch addresses the lower-level race condition during …
=> Fix Race Condition in Parsing Line Map for NVIDIA Binaries

common/src/arch-x86.C
Support decoding of XOP instructions from horizontal add/sub group. Previously there were only IDs for them, and empty decoding tables.
Code sample for testing purposes:
```
_start:
vphaddbw %xmm3, %xmm1
vphaddbw 0x123(%rbx,%rcx,4), %xmm1
vphaddbd %xmm3, %xmm1
vphaddbd 0x123(%rbx,%rcx,4), %xmm1
vphaddbq %xmm3, %xmm1
vphaddbq 0x123(%rbx,%rcx,4), %xmm1
vphaddwd %xmm3, %xmm1
vphaddwd 0x123(%rbx,%rcx,4), %xmm1
vphaddwq %xmm3, %xmm1
vphaddwq 0x123(%rbx,%rcx,4), %xmm1
vphadddq %xmm3, %xmm1
vphadddq 0x123(%rbx,%rcx,4), %xmm1
vphaddubw %xmm3, %xmm1
vphaddubw 0x123(%rbx,%rcx,4), %xmm1
vphaddubd %xmm3, %xmm1
vphaddubd 0x123(%rbx,%rcx,4), %xmm1
vphaddubq %xmm3, %xmm1
vphaddubq 0x123(%rbx,%rcx,4), %xmm1
vphadduwd %xmm3, %xmm1
vphadduwd 0x123(%rbx,%rcx,4), %xmm1
vphadduwq %xmm3, %xmm1
vphadduwq …
```
=> x86: support XOP horizontal add/sub instructions

common/h/mnemonics/x86_entryIDs.h, common/src/arch-x86.C, dataflowAPI/src/convertOpcodes.C
Intel manual define 3 different UD instructions: UD0, UD1, and UD2. UD2 is fully supported by Dyninst, UD0 and UD1 are not.
Code sample to test the change:
```
_start:
ud0 %eax, %edx
ud0 (%eax), %edx
ud1 %eax, %edx
ud1 (%eax), %edx
ud0 %rax, %rdx
ud0 (%rax), %rdx
ud1 %rax, %rdx
ud1 (%rax), %rdx
ud2 
```
Objdump:
```
0000000000001000 <_start>:
1000:	0f ff d0             	ud0    %eax,%edx
1003:	67 0f ff 10          	ud0    (%eax),%edx
1007:	0f b9 d0             	ud1    %eax,%edx
100a:	67 0f b9 10          	ud1    (%eax),%edx
100e:	48 0f ff d0          	ud0    %rax,%rdx
1012:	48 0f ff 10          	ud0    (%rax),%rdx
1016:	48 0f b9 d0          	ud1    %rax,%rdx
101a:	48 0f b9 10          	ud1    (%rax),%rdx
101e:	0f 0b                	ud2
```
Dyninst without changes:
```
"_start" :
1000: …
```
=> x86: handle UD0 and UD1 instructions

common/src/arch-x86.C, instructionAPI/src/InstructionDecoder-x86.C
Some combinations of operand types resulted in ModRM not being read. Read ModRM when we encounter an operand that references r/m field.
Fill REX fields from VEX prefix so that we can choose correct argument size in decodeAVX function.
Code asm to test:
```asm
_start:
blsr %rdx, %rcx
blsr %edx, %ecx
```
Result before the changes:
```
0000000000401000 <_start>:
401000:       c4 e2 f0 f3 ca          blsr %edx,%xmm1
401005:       c4 e2 70 f3 ca          blsr %edx,%xmm1
```
Result with the changes:
```
0000000000401000 <_start>:
401000:       c4 e2 f0 f3 ca          blsr %rdx,%rcx
401005:       c4 e2 70 f3 ca          blsr %edx,%ecx
```
=> x86: correctly decode 32 and 64 bit arguments of AVX instructions

instructionAPI/h/Result.h
There are two missing return statements in Result.h.
=> Fix compiler error in PR 1733

dataflowAPI/src/RoseInsnFactory.C
The use of reserve instead of resize for the operand vector somehow cause Dyninst to segmentation fault on test cases with GETPC, SETPC and SWAPPC.
=> Fix vector segmentation fault introduced in #1733

symtabAPI/src/indexed_symbols.hpp
new compilers warned that std::remove result was ignored as this is almost always an error.  Saved the result and used in a call to the container's erase method to actually delete the elements.
=> fix usage of remove algorithm

common/h/compiler_diagnostics.h
gcc 13 & 14 warn about boost:optional suppress just like gcc 12
=> warning fix: gcc 13,14 maybe-uninitialized

cmake/DyninstWarnings.cmake
Increase the stack size for clang 18 just like 13-17
=> fix clang 18 DEBUG stack frame size warning

common/h/Annotatable.h, dynC_API/src/C.y, dynC_API/src/dynC.tab.C
- fix order of calloc arguments that gcc 14 warns about: the correct order is number of elements, then size of elements
- fix buffer in one of the calloc calls: the number of elements calculations did not incorporate 13-bytes of output
=> fix issues with calloc calls (order/overflow)

dataflowAPI/src/SymEvalPolicy.h, symtabAPI/h/Aggregate.h, symtabAPI/h/Function.h, symtabAPI/h/Module.h, symtabAPI/h/Region.h, symtabAPI/h/Variable.h, symtabAPI/src/Aggregate.C, symtabAPI/src/Function.C, symtabAPI/src/Module.C, symtabAPI/src/Region.C, symtabAPI/src/Variable.C
In C++20 and later the signature of operator== should be T::operator==(const T&) const otherwise it is ambiguous as C++ 20 and later also looks for matching function with the arguments reversed and if only one is const then reversing results in two distinct function signatures that match equally well.  Some of these were reported as compiler warnings, others from manual inspection.
=> warning fix: ambiguous-reversed-operator

.github/workflows/compiler-multibuild.yaml
- replace ubuntu 23.10 with ubuntu 24.04
- add new compilers:  gcc 14 and clang 18
- test C++20 and C++23 with clang as it now builds without warnings
- use gcc-14 and clang-18 to test C++ 11, 14, 17, 20 and 23
=> update compiler-multibuild with new OS & compilers

.github/workflows/libabigail.yaml
- update download-artifact to 4.1.8 (eliminates security warning from dependabot that doesn't apply)
- update upload-artifact to 4.4 to be compatible with download
This is a correct fix for the dependabot suggested fix in #1773.  That patch does not update the upload-artifact and both need to be updated to be compatible. This workflow is not enabled and is untested,
=> update versions of github workflow actions

symtabAPI/src/LineInformation.C
Single address line map entries can be passed to this function as a range with the low and high address being equal.  If so, adjust the range to the correct closed, open range [low, low + 1)
Partial fix for #1763.
=> support single address line map entries

cmake/DyninstConfig.cmake.in, cmake/DyninstLibrary.cmake, dwarf/CMakeLists.txt, dyninstAPI/CMakeLists.txt, elf/CMakeLists.txt, stackwalk/CMakeLists.txt, symtabAPI/CMakeLists.txt
It's only used internally, so it shouldn't be exported. This will also make supporting other files formats (e.g., Windows PE) easier since we can properly hide those details.
This will cause link failures for consumers that explicitly pass `-ldyn{Dwarf,Elf}`. I'll run the consumers workflow to check for this, but I'm fairly certain I'll need to send patches to systemtap and TAU.
This will also cause a couple of failures in dyninst/external-tests because it tries to compile the dyn{Elf,Dwarf} headers. I'll post a PR to remove those tests.
=> Remove elfutils from public dependencies

.github/actions/os-versions/action.yaml, .github/workflows/consumers.yaml
This was introduced by d9fc07182.
I also fixed the action failures for ubuntu-24.10 and fedora-4{0,1} due to incorrect access permissions on those packages.
=> GitHub CI: fix spelling of Ubuntu 24.04 name

symtabAPI/src/dwarfWalker.C
Fixes #1787
The underyling problem in #1787 is that the upper bound of the subrange is computed from a formal function parameter. It's not clear if that idiom is specific to Fortran, but it's something that should be added to subrange [parsing](https://github.com/dyninst/dyninst/blob/master/dwarf/src/dwarf_subrange.cpp#L61).
=> Check for valid subrange bounds in DwarfWalker::parseSubrange()

.github/workflows/consumers.yaml
Oddly, the `-tbb` option doesn't care if the libraries are in /usr/lib or /usr/lib64. I've tested it successfully on both Ubuntu-24.10 and Fedora-41 containers.
=> GitHubCI: update TAU test

.github/workflows/pr-tests.yaml, cmake/DyninstConfig.cmake.in
Currently in some scenarios (e.g. Debian multiarch `/usr`), the generated `DyninstConfig.cmake` is unable to find the matching include directory to set the legacy `DYNINST_INCLUDE_DIR` variable. Dyninst users trying to use a Dyninst installed as such are thus greeted with the following error, regardless of whether they actually use the legacy variable:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Dyninst/DyninstConfig.cmake:32 (message):
File or directory /usr/lib/x86_64-linux-gnu/cmake/Dyninst/../../../include
referenced by variable DYNINST_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
/usr/lib/x86_64-linux-gnu/cmake/Dyninst/DyninstConfig.cmake:65 (set_and_check)
CMakeLists.txt:1 (find_package)
```
This PR replaces the hardcoded include path relative to the …
=> Fix DyninstConfig for Debian multiarch installs

cmake/tpls/DyninstBoost.cmake
Currently Dyninst can only find Boost if it has a `BoostConfig.cmake` (implied by the `find_package(... HINTS ...)` keyword). Some notable distros, specifically RHEL 9.x, have a new enough Boost to build Dyninst but do not package `BoostConfig.cmake`, which breaks the build.
This PR removes the `HINTS` syntax and allows using the `FindBoost.cmake` module shipped with CMake, which supports common variables like `BOOST_ROOT`, works without `BoostConfig.cmake`, and supports older versions of Boost.
=> Fix Boost not found error on RHEL 9

dyninstAPI/src/addressSpace.C, dyninstAPI/src/addressSpace.h
It was added by fb2612c0fac in 2007, but never used.
=> Remove addressSpace::findJumpTargetFuncByAddr

instructionAPI/doc/API/Instruction.tex, instructionAPI/doc/API/Operand.tex, instructionAPI/doc/API/Operation.tex, instructionAPI/h/Instruction.h, instructionAPI/h/Operand.h, instructionAPI/h/Operation_impl.h, instructionAPI/src/Instruction.C, instructionAPI/src/InstructionDecoder-x86.C, instructionAPI/src/Operand.C, instructionAPI/src/Operation.C
These classes will need non-trivial modifications for the move to Capstone. This makes them easier to work with.
=> Clean up Operand, Operator, and Instruction classes from InstructionAPI

dataflowAPI/src/liveness.C, dataflowAPI/src/stackanalysis.C, dyninstAPI/src/BPatch_basicBlock.C, dyninstAPI/src/Relocation/CFG/RelocBlock.C, dyninstAPI/src/Relocation/Transformers/Movement-adhoc.C, dyninstAPI/src/Relocation/Transformers/Movement-analysis.C, dyninstAPI/src/StackMod/StackAccess.C, dyninstAPI/src/ast.C, dyninstAPI/src/hybridInstrumentation.C, dyninstAPI/src/image.C, dyninstAPI/src/mapped_object.C, instructionAPI/h/Instruction.h, instructionAPI/src/Instruction.C, parseAPI/src/IA_IAPI.C, parseAPI/src/IA_aarch64.C, parseAPI/src/IA_amdgpu.C, parseAPI/src/IA_power.C, parseAPI/src/IA_x86.C, parseAPI/src/IndirectAnalyzer.C, parseAPI/src/Parser.C
getCategory() assumes there is only one category per instruction, but that restriction will be removed when using the Capstone decoder and the function deprecated. These helpers will make it easier for users to check behavior without having to know how it's being tracked in Instruction.
This makes IA_IAPI::hasCFT() more expensive, but it will be much cheaper as we move more architectures to Capstone.
=> Add category helpers to Instruction class

instructionAPI/h/Instruction.h, instructionAPI/src/Instruction.C, instructionAPI/src/InstructionDecoder-aarch64.C, instructionAPI/src/InstructionDecoder-power.C, instructionAPI/src/InstructionDecoder-x86.C
Instruction::makeReturnInstruction always assumes a 32-bit unsigned value is read from the top of the stack. This is not true for Aarch64 and ppc64le (and probably not for RISCV). In fact, ppc and x86 (kind of) already create AST for return instructions, but it gets ignored by Instruction::getControlFlowTarget.
=> Use correct semantics when constructing AST for return instructions

dataflowAPI/src/liveness.C, instructionAPI/h/Instruction.h, instructionAPI/h/InstructionCategories.h, instructionAPI/src/Instruction.C, parseAPI/src/IA_IAPI.C
@kupsch I *think* the name here should be fine. We don't really model hardware interrupts, but I want to add another category for halt/abort/reset instructions for the port to Capstone. These are kind of handled in [`IA_IAPI::isAbort`](https://github.com/dyninst/dyninst/blob/master/parseAPI/src/IA_IAPI.C#L320). I'm not sure what that category should be called, but c_HardwarInterruptInsn doesn't seem like a good one since it might suggest we also model UART-like interrupts.
=> Add instruction class for software interrupts

instructionAPI/doc/API/Instruction.tex, instructionAPI/h/InstructionCategories.h, instructionAPI/src/InstructionCategories.C
`c_TransactionalInsn` is new and will be used when migrating to Capstone.
=> Clean up, extend, and document Instruction categories

instructionAPI/h/InstructionDecoder.h
This allows for safer assumptions in the upcoming Capstone-base decoders. It also makes no sense for users to call this, and was never documented.
=> Make InstructionDecoder::doDelayedDecode private

dyninstAPI/src/BPatch_snippet.C, dyninstAPI/src/BPatch_type.C, dyninstAPI/src/IAPI_to_AST.C, dyninstAPI/src/RegisterConversion-aarch64.C, dyninstAPI/src/RegisterConversion-ppc.C, dyninstAPI/src/RegisterConversion-x86.C, dyninstAPI/src/RegisterConversion.h, dyninstAPI/src/Relocation/Widgets/PCWidget-aarch64.C, dyninstAPI/src/Relocation/Widgets/PCWidget-ppc.C, dyninstAPI/src/Relocation/Widgets/PCWidget-x86.C, dyninstAPI/src/ast.C
Confirmed builds on x86, arm, and ppc.
=> Remove unused parameter from dyninstAPI/convertRegID

common/h/registers/aarch64_regs.h, instructionAPI/capstone/aarch64/registers.py, instructionAPI/capstone/aarch64/sysregs.py
The test suite is still failing on arm with these changes, but they are ~3 levels down in the stack to fix those failures.
=> Update aarch64 registers for Capstone 6

dwarf/h/dwarfFrameParser.h, dwarf/src/dwarfFrameParser.C
When running with ~4 or more threads, there is an intermittent crash during the destruction of frameParsers.
=> Fix crash in DwarfFrameParser::create

dwarf/h/dwarfHandle.h, dwarf/src/dwarfHandle.C, elf/h/Elf_X.h, elf/src/Elf_X.C
These caches are thread-unsafe, but instances of this class can be created by multiple threads simultaneously. Crashes were observed when running the test suite. The tests would pass, but then the processes would crash when being reaped.
=> Fix crashes in Elf_X and DwarfHandle

dataflowAPI/src/AbslocInterface.C, dataflowAPI/src/RoseInsnFactory.C, dataflowAPI/src/stackanalysis.C, dyninstAPI/src/BPatch_memoryAccessAdapter.C, dyninstAPI/src/Relocation/Transformers/Movement-adhoc.C, dyninstAPI/src/StackMod/StackAccess.C, instructionAPI/doc/API/Instruction.tex, instructionAPI/doc/examples/Visitor-regexample.C, instructionAPI/h/Instruction.h, instructionAPI/src/Instruction.C, instructionAPI/src/InstructionDecoder-aarch64.C, instructionAPI/src/syscalls.C, parseAPI/src/BoundFactCalculator.C, parseAPI/src/IA_x86.C, parseAPI/src/IndirectAnalyzer.C, parseAPI/src/JumpTableFormatPred.C, parseAPI/src/Parser.C, parseAPI/src/ProbabilisticParser.C
There are many places in Dyninst where only one type of operand is needed. This removes the need to do the filtering at those code points and allows for possibly expanding what an implicit register is (e.g., vector mask registers in some cases).
Deprecates Instruction::getOperands(std::vector<Operand>).
=> Separate operand interface in Instruction class

instructionAPI/src/InstructionDecoder-aarch64.C, instructionAPI/src/InstructionDecoder-power.C
These were introduced by 902c6d3107. For aarch64, other parts of Dyninst assume that there is no AST for the implicit
case, causing test suite failures. On ppc, the bcIsConditional wasn't enough to determine if this is a return-from-
function instruction.
These tested fine on x86, aarch64, and ppc machines at UOregon's Frank enclave before I merged them. However, they are causing test failures on other machines on all platforms. I guess I'm going to have to start testing on a dozen machines before I can make any further changes to the decoders.
=> Fix return semantics on aarch64 and ppc

instructionAPI/h/Instruction.h
clang prefers this ordering of attributes. I'm not sure if this is mandated by the standard or just a clang QoI issue.
This wasn't caught by CI testing because I forgot to specify the compiler when building external-tests and unit-tests in the pr-tests workflow. I'll fix that separately.
=> Fix attribute ordering in deprecated Instruction::getOperands

.github/workflows/cmake-formatting.yaml, .github/workflows/dependency-version.yaml, .github/workflows/libabigail.yaml, .github/workflows/pr-tests.yaml
This will make sure the workflows run after converting a draft to 'ready for review'.
=> GitHubCI: expand events that trigger workflows

.github/actions/build/action.yaml
This will allow the build action to be used in other repos.
=> GitHubCI: re-use source checkout in build action

common/h/registers/MachRegister.h, common/src/registers/MachRegister.C, dataflowAPI/CMakeLists.txt, dataflowAPI/rose/RegisterDescriptor.h, dataflowAPI/rose/registers/aarch64.h, dataflowAPI/rose/registers/amdgpu.h, dataflowAPI/rose/registers/convert.C, dataflowAPI/rose/registers/convert.h, dataflowAPI/rose/registers/ppc32.h, dataflowAPI/rose/registers/ppc64.h, dataflowAPI/rose/registers/x86.h, dataflowAPI/rose/registers/x86_64.h, dataflowAPI/src/ExpressionConversionVisitor.C, external/rose/amdgpuInstructionEnum.h, external/rose/armv8InstructionEnum.h
The conversion is only ever used in dataflowAPI, so that's where it belongs. It also simplifies the conversion by directly creating a `RegisterDescriptor` which is the register vocabulary for interacting with ROSE.
There are several bugs that I will submit fixes for in separate PRs, notably in `SymEvalSemantics::RegisterStateAST::convert`.
@bbiiggppiigg Could you double-check the GPU changes?
=> Move MachRegister -> ROSE register conversion into dataflowAPI

dyninstAPI/src/inst-aarch64.C, dyninstAPI/src/parse-aarch64.C
The MachRegister ids are no longer guaranteed to be sequential, so performing arithmetic on them may not be valid. Because 'registerSlot' uses aarch64Registers_t to represent registers, MachRegisters need to be transformed using the conversion maps in RegisterConversion-aarch64.C. Those maps use the the base registers `x<N>` for GPRs and `q<N>` for FPRs, so the registers are correspondingly transformed before being stored in parse_func::usedRegisters.
@kupsch This fixes almost all test failures on zeroah. I'm working on the rest.
=> Fix register calculation in parse_func::calcUsedRegs for aarch64

instructionAPI/doc/API/Instruction.tex, instructionAPI/src/Instruction.C, parseAPI/src/IA_IAPI.C, parseAPI/src/IndirectAnalyzer.C
These only detect actual decode failures on x86.
'isValid' was added by 410f34166 in 2008 and 'isLegalInsn' by b490edd40 in 2009. It's unclear why the latter was needed.
@bbiiggppiigg Is there a reason the AMD GPU opcodes don't have an invalid entryID?
=> Unify valid instruction detection

dyninstAPI/src/inst-power.C, dyninstAPI/src/parse-power.C
The MachRegister ids are no longer guaranteed to be sequential, so performing arithmetic on them may not be valid. Because 'registerSlot' uses powerRegisters_t to represent registers, MachRegisters need to be transformed using the conversion maps in RegisterConversion-ppc.C.
=> Fix register calculation in parse_func::calcUsedRegs for ppc

common/src/registers/MachRegister.C
The individual flag registers (e.g., x86::zf) get mapped to the whole register (e.g., x86::flags).
=> Don't use base register in isZeroFlag

common/src/registers/MachRegister.C
Currently, this treats every field in each group as being a zero flag. Since we have representations for each bit in the field, then only the EQ flag should be checked here.
=> Fix MachRegister::isZeroFlag for ppc

common/h/registers/aarch64_regs.h, common/src/registers/MachRegister.C, instructionAPI/capstone/aarch64/registers.py
This gives the same semantics as for flag registers on the other platforms.
It doesn't look like Capstone has a representation for 'pstate'. I'll update the importer once the aarch64 decoder is migrated.
=> Update aarch64 flag and pstate registers

common/src/registers/MachRegister.C
OpenPOWER Foundation
Power Instruction Set Architecture
Version 3.1C
May 26, 2024
4.2 Floating-Point Facility Registers
3.2 Fixed-Point Facility Registers
6.3 Vector Facility Registers
7.2 VSX Registers
Unit tests are passing: https://github.com/dyninst/unit-tests/pull/12
=> Fix base register calculation for ppc

dataflowAPI/src/RoseInsnFactory.C
The ROSE semantics only handle the explicit operands.
=> Fix operand fetch in RoseInsnFactory::convert

dataflowAPI/rose/semantics/DispatcherARM64.C, dataflowAPI/rose/semantics/DispatcherARM64.h, dataflowAPI/rose/semantics/Registers.C
This is based on the latest ROSE source. Fixes two aarch64 test suite failures.
Requires #1859
=> Add executor for aarch64 return instruction

common/src/registers/MachRegister.C
PowerPC uses specific general-purpose registers for special registers like the frame pointer, stack pointer, etc.
Requires #1864
=> Use correct ppc32/64 base registers in is* checks

common/src/registers/MachRegister.C, dataflowAPI/rose/registers/aarch64.h, dataflowAPI/rose/registers/convert.C
I plan to refactor the entire rose conversion process to get rid of the assumptions about the sequence of register IDs.
@kupsch New rule: I am no longer allowed to do refactorings without unit tests. This is just embarrassing.
=> Fix rose register conversion for aarch64

dataflowAPI/src/RoseInsnFactory.C
Previous implementation assumed the existence of allOperands instead of just explicitOperands.
This change is required to reflect the changes made in #1859.
=> Fix AMDGPU rose to use explicit operands

dyninstAPI/src/inst-aarch64.C
This also switches to using `Instruction::getControlFlowTarget` to get the correct CFT.
=> Fix MachRegister conversion in getDynamicCallSiteArgs for aarch64

common/src/sha1.C
Subject header is needed on gcc15 to compile sha1.C, supplying declaration of types like uint32_t.
=> Update sha1.C: #include <cstdint>

dyninstAPI/src/parse-power.C
Only gcc-8 caught this. I'm not sure why.
=> Fix PowerPC flag checks in parse_func::calcUsedRegs

common/h/registers/AMDGPU/amdgpu_gfx908_regs.h, common/h/registers/AMDGPU/amdgpu_gfx90a_regs.h, common/h/registers/AMDGPU/amdgpu_gfx940_regs.h, dataflowAPI/rose/registers/amdgpu.h, dataflowAPI/rose/semantics/Registers.C, dataflowAPI/rose/semantics/SymEvalSemantics.C, external/rose/amdgpuInstructionEnum.h
1. Unify register definitions for GFX908 with 90A and 940
a. Separate WAITCNT into a separate register class
b. Move SCC into MISC class
c. Fix wrong index number for hw_reg_ib_sts
2. Update rose AMDGPU enum to reflect the relavnt changes
a. Each MISC type register should have a minor enum value matching
its index number
3. Update the register descriptor creation logic casting the index
4. Update the register conversion logic in rose
a. Remove the case for hardware register as scc is moved to MISC
b. Add the case for handling the MISC registers
=> refactor amdgpu register handling

dataflowAPI/src/SymEval.C
Disable simplifyStack for AMDGPU as it is causing segmentation fault when paring certain AMDGPU binaries, 
when OMP_NUM_THREADS!=1. T
The problem seems to be related the maps in Annotatable.h needs to be thread safe.
=> Disable simplifyStack for AMDGPU

common/src/arch-aarch64.h, common/src/registers/MachRegister.C, dataflowAPI/rose/registers/aarch64.h, dataflowAPI/rose/registers/convert.C, dataflowAPI/src/AbslocInterface.C, dataflowAPI/src/RegisterMap.C, dyninstAPI/src/RegisterConversion-aarch64.C, dyninstAPI/src/inst-aarch64.C, dyninstAPI/src/registerSpace.h, instructionAPI/src/InstructionDecoder-aarch64.C, proccontrol/src/linux.C
This should have been part of #1866
=> Separate usage of aarch64 pstate and nzcv flag registers

.github/workflows/consumers.yaml
The spack update https://github.com/spack/spack/pull/47637 somehow broke the hpctoolkit install when using the sources in /dyninst/install on Ubuntu-24.10 and Fedora-41. This change has the added benefit of making the usage of spack for building hpctoolkit more idiomatic.
=> GithubCI: use spack-provided dyninst when building hpctoolkit

dataflowAPI/rose/semantics/DispatcherARM64.C
Fix the handling for ldp_gen_execute
(address should be args[2], immediate args[3])
https://developer.arm.com/documentation/ddi0602/2024-12/Base-Instructions/LDP--Load-pair-of-registers-
Fix the handling for ldursw
(immediate args[2] is optional)
https://developer.arm.com/documentation/ddi0602/2024-12/Base-Instructions/LDURSW--Load-register-signed-word--unscaled--?lang=en#simm
=> Fix ROSE expansion of aarch64 ldp, ldurs instructions

symtabAPI/h/Function.h, symtabAPI/h/Region.h, symtabAPI/h/Symbol.h, symtabAPI/h/Symtab.h, symtabAPI/src/Function.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.C, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C, symtabAPI/src/emitElf.C, symtabAPI/src/emitElf.h, symtabAPI/src/parseDwarf.C
This change is made in preparation for implementation of PE files parsing support.
The base class AObject is renamed to Object and its interface is expanded.
Derived classes now have different names depending on the type of the object files they represent, e.g. ObjectELF
All non-specific parsing operations were changed to work with the basic class.
A new function that selects derived class based on magic bytes is implemented. It can only select ObjectELF for now.
=> Refactroing of AObject class

common/h/util.h, common/src/util.C
These aren't and shouldn't be used. Using these types as keys in hashed
associative containers is fraught with danger.
Requires #1901
=> Remove pointer/address hashers in common/util

common/h/util.h, common/src/util.C
These are no longer needed since C++11's std::to_string.
Requires https://github.com/dyninst/testsuite/pull/254
=> Remove string conversion functions in common/util

dyninstAPI/src/image.C, dyninstAPI/src/image.h, dyninstAPI/src/unix.C, symtabAPI/h/Symtab.h, symtabAPI/h/symutil.h, symtabAPI/src/Module.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C
ObjectType is internal to Object class. It can be different for different object file formats. Other code should be using accessors isExecutable(), isSharedLibrary(), etc.
=> Deprecate Object::getObjectType()

symtabAPI/CMakeLists.txt, symtabAPI/h/Function.h, symtabAPI/h/Region.h, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-pe.C, symtabAPI/src/Object-pe.h, symtabAPI/src/Object.C, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C
This is a next step towards support of PE files parsing.
A dummy ObjectPE class is defined. Actual parsing is not implemented yet.
=> Define ObjectPE

common/h/util.h, common/src/util.C
It was never documented, and it hasn't been maintained (there's no string for FreeBSD or aarch64).
=> Remove platform_string()

symtabAPI/h/Symtab.h
It was added by 6b8446ea6f in 1999, but never used.
=> Remove Symtab::main_call_addr_

tests/regression/symtabAPI/Symtab/file_properties/CMakeLists.txt
This only happened to work on ubuntu because the gcc there accepts `-f[no-]PIE` as an equivalent to `-[no-]pie`. Fedora's gcc does not use that.
=> Correctly test PIE binaries in regression tests

dyninstAPI/CMakeLists.txt, dyninstAPI/src/image.C
It's not actually needed. Binary rewriting uses dynElf and dynDwarf, though.
=> Remove elfutils dependency from dyninstAPI

dwarf/h/dwarfHandle.h, symtabAPI/src/Archive-elf.C, symtabAPI/src/Function.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.C, symtabAPI/src/Object.h, symtabAPI/src/emitElf.h, symtabAPI/src/emitElfStatic-aarch64.C, symtabAPI/src/emitElfStatic-ppc64.C, symtabAPI/src/emitElfStatic-x86.C, symtabAPI/src/parseDwarf.C
This was causing unnecessary build failures.
=> Don't include platform-specific Object headers in Object.h

dataflowAPI/rose/registers/ppc64.h
Dyninst treats them as the whole register, but ROSE splits them up.
The values come from `RegisterDictionary::dictionary_powerpc`.
=> Fix ROSE register size for ppc64 CR registers

common/CMakeLists.txt, common/src/MappedFile.C, common/src/addrtranslate-linux.C, common/src/addrtranslate-sysv.C, common/src/dyninst_filesystem.C, common/src/dyninst_filesystem.h, dyninstAPI/src/dynProcess.C, dyninstAPI/src/freebsd.C, dyninstAPI/src/image.C, dyninstAPI/src/linux-x86.C, dyninstAPI/src/unix.C, proccontrol/src/linux.C, proccontrol/src/loadLibrary/codegen-freebsd.C, proccontrol/src/windows_handler.C, symtabAPI/src/Module.C, symtabAPI/src/Symtab-edit.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C, symtabAPI/src/dwarfWalker.C, symtabAPI/src/emitElf.C, symtabAPI/src/parseDwarf.C, tests/unit/common/CMakeLists.txt, tests/unit/common/filesystem.cpp
I prefer free functions to be verbs, so I chose `canonicalize` over `boost::filesystem::canonical` and `extract_filename` over the member function `boost::filesystem::path::filename`.
=> Rename, namespace pathName functions

dyninstAPI/src/BPatch_binaryEdit.C
The compilers should have warned about these.
=> Remove unused variables in BPatch_binaryEdit constructor

dyninstAPI/src/binaryEdit.C
The `new` operator can't return null in this case.
=> Remove unnecessary check in BinaryEdit::openFile

dyninstAPI/src/binaryEdit.C, dyninstAPI/src/binaryEdit.h
It's only used in the one spot, so just make it a local variable declaration.
=> Remove binaryEdit::getStatFileDescriptor

common/src/MappedFile.C, common/src/MappedFile.h, dyninstAPI/src/BPatch.C, dyninstAPI/src/BPatch_binaryEdit.C, dyninstAPI/src/image.C, dyninstAPI/src/image.h, symtabAPI/h/Archive.h, symtabAPI/h/Collections.h, symtabAPI/h/Module.h, symtabAPI/h/Symbol.h, symtabAPI/h/Symtab.h, symtabAPI/src/Archive-elf.C, symtabAPI/src/Archive.C, symtabAPI/src/Collections.C, symtabAPI/src/Module.C, symtabAPI/src/Region.C, symtabAPI/src/Symbol.C, symtabAPI/src/Symtab-edit.C, symtabAPI/src/Symtab-lookup.C, symtabAPI/src/Symtab.C
I was chasing down an unrelated bug and kept running into corrupted `std::string`s- probably from a life-extended temporary getting modified. This fixes that issue.
=> Clean up and refactor string handling in parts of SymtabAPI and DyninstAPI

CMakeLists.txt, cmake/DyninstOptions.cmake, cmake/tpls/DyninstPeParse.cmake, dyninstAPI/CMakeLists.txt, symtabAPI/CMakeLists.txt, symtabAPI/src/Object-pe-stub.C, symtabAPI/src/Object-pe.C, symtabAPI/src/Object-pe.h
Header and sections are parsed. Entry point is detected. Some parsing of .EXE files can be done.
Not supported yet: symbols, relocations.
=> Initial implementation of PE files parsing

cmake/tpls/DyninstElfUtils.cmake, cmake/tpls/DyninstLibIberty.cmake, cmake/tpls/DyninstThread_DB.cmake, cmake/tpls/DyninstThreads.cmake
Since they don't have actual source files, then CMake requires them to be imported.
=> Mark CMake dummy targets as IMPORTED

instructionAPI/h/Instruction.h, instructionAPI/src/AMDGPU/gfx908/amdgpu_gfx908_decoder_impl.C, instructionAPI/src/AMDGPU/gfx90a/amdgpu_gfx90a_decoder_impl.C, instructionAPI/src/AMDGPU/gfx940/amdgpu_gfx940_decoder_impl.C, instructionAPI/src/Instruction.C
AMDGPU instructions could use a 32 bit instruction literall following the current instruction.
However, whether a instruction uses a literal can only be determined after parsing the operands.
Previous approach crafts a instruction first and then update the bytes if a literal is beng used, but the 
copy of raw bytes is copied only during the construction of the instruction.
This PR updated the implementation of updateSize to copy the literal bytes.
=> Fix copying missing constant instruction literal

instructionAPI/h/Result.h
When Result object is not defined, its `type` field may be uninitialized or contain a meaningless value. Thus check the `defined` field first.
Also the case `type > o.type` was missing, which may lead to an incorrect comparison.
The issue was highlighted by Valgrind.
=> Fix possible use of uninitialized value in Result::operator<

.github/workflows/pr-tests.yaml, docker/build.sh
This is needed on Fedora where, for a yet-unknown reason, the RUNPATH does not include /usr/lib even though
1) DYNINST_FORCE_RUNPATH=ON
2) `ldd libsymtabAPI.so` clearly shows that pe-parse.so resolves to /usr/lib/pe-parse.so.
Even more vexxing is that it works correctly when the idential container and commands are run locally (i.e., not in GitHub).
=> GitHubCI: add /usr/lib to LD_LIBRARY_PATH

.github/workflows/consumers.yaml
There's a bug in their config I haven't been able to fix, so just exclude it for now.
=> GitHubCI: don't build extrae on ubuntu-24.10

symtabAPI/src/parseDwarf.C
This one isn't used. There is another copy in Object-nt.C that is.
=> Remove SymtabAPI convertCharToString

dataflowAPI/src/ExpressionConversionVisitor.C, parseAPI/src/IndirectAnalyzer.C
Don't assert or SEGV during indirect jump analysis if analysis can't proceed because an AST node is NULL.
If analysis yields a NULL AST node, analysis is simply over.
=> adjust handling for indirect jump analysis for AMD GPUs

cmake/Modules/DyninstCheck32bitRuntimeSupported.cmake, dyninstAPI_RT/CMakeLists.txt
Requires #1965 
This also fixes a bug in the filename generated for the 32-bit static dyninstAPI_RT.
=> CMake: update detection of 32-bit runtime

dyninstAPI/h/BPatch_image.h, dyninstAPI/src/BPatch_image.C
This method enables getting the filename without knowing the length.
It is used in #1802 for spitting out a file with instrumented kernel names from the GPU code object.
=> [BPatch] Add API function std::string BPatch_image::getProgramFileName()

parseAPI/src/IA_IAPI.C, parseAPI/src/IA_amdgpu.C, parseAPI/src/IA_amdgpu.h, parseAPI/src/Parser.C
This is the correct fix for the problem of duplicated s_endpgm, which happens if a basic block starts with s_endpgm.
=> Handle s_endpgm as an aborting instruction

dyninstAPI/src/Relocation/CFG/RelocBlock.C, instructionAPI/h/Instruction.h, instructionAPI/h/InstructionCategories.h, instructionAPI/src/InstructionCategories.C, parseAPI/h/InstructionAdapter.h, parseAPI/src/IA_IAPI.C, parseAPI/src/IA_IAPI.h, parseAPI/src/IA_amdgpu.C, parseAPI/src/IA_amdgpu.h, parseAPI/src/Parser.C
Rename isAbort to SoftwareExcpetion, and add the corresponding instructions that fits this category.
Also remove isAbort/isSoftwareException implementation for AMDGPU in IA_IAPI.
=> Add SoftwareException instruction category

instructionAPI/src/AMDGPU/gfx908/finalizeOperands.C, instructionAPI/src/AMDGPU/gfx90a/finalizeOperands.C, instructionAPI/src/AMDGPU/gfx940/finalizeOperands.C
There was a bug that causes implicit operands to have a fix operand length of 1.
As a result, operands EXEC (exec_lo+exec_hi) is being treated as a single EXEC.
This PR fixes the problem.
Fixes for other implicit operands will come when we finally get a new ISA drop (hopefuly soon).
=> Fix EXEC operand for AMDGPU

.github/actions/os-versions/action.yaml, .github/scripts/compiler_configs.py, .github/workflows/README.md, .github/workflows/compiler-multibuild.yaml, .github/workflows/refresh-containers.yaml, cmake/DyninstWarnings.cmake, common/h/compiler_diagnostics.h, docker/README.md, docker/build_peparse.sh
I have no idea why clang-16 has no package for Ubuntu 25. I haven't checked for a ppa, but we still have it in Fedora 37.
Ubuntu 25.10 is the same set of compilers, but has glibc 2.42. I didn't think it was really worthwhile to add it since Fedora 43 is effectively that same case.
=> Docker: remove Ubuntu 24. Add Ubuntu 25, Fedora 42, 43

dataflowAPI/src/ABI.C, dataflowAPI/src/RegisterMap.C
DataflowAPI portion of #1987.
Requires #2003.
=> [AMDGPU][DataflowAPI] Add missing registers for gfx908

dyninstAPI/src/emit-x86.C
This was found by building on an x86 host with
-DDYNINST_CODEGEN_ARCH=i386.
=> Fix unused function warning in x86-emit.C with i386 codegen on x86_64 host

symtabAPI/src/emitElfStatic-stub.C
Fix some of the errors in #2007.
Probably no longer need emitElfStatic-amdgpu in #1987
=> Fix default implementation in emitElfStatic-stub

dyninstAPI/src/emit-x86.C
This was found when building with clang-20.
=> Fix unused variable warning in emit-x86 for i386 codegen

dyninstAPI/src/ast.C
For architectures that don't support stack modifications (cap_stack_mods)- currently only x86/x86_64 do- these member variables are not used.
Found when compiling with clang-21.
=> Fix unused private variables in AstStackRemoveNode

symtabAPI/src/emitElfStatic-ppc64.C, symtabAPI/src/emitElfStatic.C
These were found when compiling with clang-21.
=> Fix cast-align warnings in emitElfStatic

.github/workflows/codegen-cross-build.yaml
Currently, GitHub CI only runs on x86_64, so we can't test all possible combinations of host and codegen architectures.
I'd like to merge this before #2006, so we can confirm it builds in CI.
=> GitHub CI: add builds for all codegen architectures

dyninstAPI/src/linux-aarch64.C, dyninstAPI/src/linux-power.C
The `getMaxBranch` function is defined in inst-<arch> files for x86, power and aarch64. It is used by both host and codegen for power and aarch64. When host and codegen arch are different (i.e building for AMDGPU), the definition will be missing for the host side. This PR is a crude fix to this issue until we figure out a cleaner solution.
=> Temporary fix for host-codegen separation on Power and AArch64

.github/workflows/consumers.yaml
1. Use their new bootstrap script
2. Remove ubuntu version check (we no longer use 24.10)
=> GitHubCI: cleanup and fix extrae build

.github/workflows/consumers.yaml
This should be reverted once https://github.com/LLNL/LaunchMON/pull/65 is merged.
=> GitHubCI: patch build error in launchmon

.github/workflows/consumers.yaml
It sometimes fails when built in parallel.
=> GitHubCI: build MRNet serially

.github/workflows/consumers.yaml
spack fails to bootstrap on Fedora 43. This can be re-enabled once https://github.com/spack/spack/issues/51410 is resolved.
=> GitHubCI: disable HPCToolkit on Fedora
