common/src/addrtranslate-win.C
=> Build fix for addrtranslate

parseAPI/src/IndirectASTVisitor.C
This should eliminate all error reporting except for the jmp to 0 ones.
=> Latest fix for rice folks

dyninstAPI_RT/src/RTcommon.c
With dynamic TLS, the call to __tls_get_addr() could reach additional
instrumented code, infinitely recursing back to check the tramp guard.
Static TLS is a limited resource, but this case in RTlib is special
enough to warrant it for safety alone, nevermind performance.
Fixes #98.
=> RTlib: use static TLS for the tramp guard

dyninstAPI_RT/src/RTheap.c
Only causes a warning with gcc, but a fatal error with VS 2015.
=> Refactor RTheap to avoid doing arithmetic with void*

.travis.yml
Should fix using clang on travis.
=> Don't use broken llvm apt mirror

dyninstAPI/src/codegen-x86.C
Fixes #111. Very small fix, will not introduce any new issues.
=> Disabled condition decoding in stack rewriting.

dataflowAPI/rose/rangemap.C, dataflowAPI/rose/util/LinearCongruentialGenerator.C, dataflowAPI/rose/util/StringUtility.C, dataflowAPI/rose/util/StringUtility.h, external/inttypes-win.h, external/stdint-win.h, parseAPI/CMakeLists.txt
Some fixes for build errors caused by #127 on both linux and windows.
=> Rose build fixes

dataflowAPI/src/stackanalysis.C
Fixes #131 
@wrwilliams Can this be merged right away?
=> Matt's patch applied -- fixes test_stack_1 issue

proccontrol/src/linux.C, proccontrol/src/loadLibrary/codegen.C
=> proccontrol: fix process attachment without an exe

dataflowAPI/src/stackanalysis.C, dyninstAPI/src/image.C, dyninstAPI/src/image.h
These changes made it into `v9.2_patches` but didn't make it into master yet.
=> Fixes for test_pt_ls

.gitignore
=> Added generated cotire directories to gitignore

dyninstAPI/src/BPatch_object.C
=> Guard StackMod implementation from non-x86 architectures.

dyninstAPI/src/image.C
The `findMain` analysis should be more accurate and less susceptible to asserts and failures. I don't have the 32 bit libraries installed on my workstation but it looked like the 64 bit tests were passing when the testsuite completed.
@wrwilliams ok to test?
=> Improved the findMain analysis significantly

parseAPI/src/IndirectASTVisitor.C, symtabAPI/src/Module.C, symtabAPI/src/dwarfWalker.C
String table now includes an entry at zero for "unknown", so don't subtract from the DWARF file number.
=> String table now includes an entry at zero for "unknown", so don't subtract from the DWARF file number.

elf/h/Elf_X.h, elf/src/Elf_X.C
=> ElfX: add xlate funcs

symtabAPI/h/Symbol.h, symtabAPI/src/Object-elf.C, symtabAPI/src/emitElf.C
Added support for the GNU Unique link type to SymtabAPI.
=> Added symbol linkage support for GNU unique linkage types

CMakeLists.txt, dynC_API/CMakeLists.txt, dynC_API/src/C.l, dynC_API/src/C.y, dynC_API/src/dynC.tab.C, dynC_API/src/dynC.tab.h, dynC_API/src/lex.dynC.C
Moved to branch for jenkins testing.
=> Make dynC work on windows

elf/src/Elf_X.C
Fixes crashes in Elf_X on ppc big-endian.
=> Use in-place translation

symtabAPI/h/Module.h, symtabAPI/src/LineInformation.C, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
Fixes that should cover test1_30 failures and give us a not-terrible fallback when we're confronted with statements that are outside of range info.
=> Line info cleanup

parseAPI/src/IA_powerDetails.C, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
Fixes for gcc 4.4 build and a couple of stupid crashes that only showed up on decently complex binaries.
=> Small fixes

symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
A few more fixes on parsing dwarf information generated by ICC
=> Release9.3/fixes/icc binaries

dyninstAPI/src/Relocation/Widgets/StackModWidget.C, dyninstAPI/src/codegen-x86.C
Fixes #311. There wasn't anything wrong with the displacement modification code except for the validation checks.
=> Displacement validation checks updated

parseAPI/src/BoundFactCalculator.C
=> Fix memory leaks in indirect control flow.

common/src/addrtranslate-sysv.C, dyninstAPI/h/BPatch_type.h, dyninstAPI/src/BPatch.C, dyninstAPI/src/BPatch_collections.C, dyninstAPI/src/BPatch_type.C, dyninstAPI/src/image.C, symtabAPI/src/Collections.C, symtabAPI/src/Type.C
Recreating #275 but rebased on v9.3.x
=> Fix memory leaks found with lsan

dyninstAPI/src/linux-aarch64.C, stackwalk/src/linux-swk.C
Targeting #313 at the 9.3 branch.
=> Suppress debug message when no vsyscall page was found on arm64

dataflowAPI/src/RegisterMap.C, dataflowAPI/src/liveness.C, dyninstAPI/src/codegen.C
Reproducing #316 targeting the 9.3 branch.
=> Use ifdef to guard x86 code

symtabAPI/h/Symtab.h, symtabAPI/src/Aggregate.C, symtabAPI/src/Module.C, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
Replaced a bunch of asserts with graceful error handling.
=> Replaced a bunch of asserts with graceful error handling.

dyninstAPI/h/BPatch_type.h, dyninstAPI/src/BPatch_type.C, dyninstAPI/src/Parsing.C, dyninstAPI/src/Relocation/Transformers/Movement-analysis.C, dyninstAPI/src/binaryEdit.h, dyninstAPI/src/dynProcess.C, dyninstAPI/src/pcEventMuxer.C, symtabAPI/h/Function.h, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object-nt.C, symtabAPI/src/Object-nt.h, symtabAPI/src/Symtab.C, symtabAPI/src/dwarfWalker.C, symtabAPI/src/emitElf.C, symtabAPI/src/emitElf.h
This should fix the remaining ABI issue on #343.
=> Refactor BPatch_type so it always has a reference to its underlying symtab type.

common/src/arch-aarch64.h, dyninstAPI/src/Relocation/CFG/RelocGraph.C, dyninstAPI/src/baseTramp.C, dyninstAPI/src/codegen-aarch64.C, dyninstAPI/src/inst-aarch64.C, dyninstAPI_RT/src/RTcommon.c
It's missing from the current master.
=> Add a macro MSROp

common/h/dyntypes.h, symtabAPI/src/Variable.C
- Fixes for bugs found during windows compilation. 
- Tested compilation and run of a single mutator on linux after the fix.
- Tested windows compilation.
=> Bugfixes windows

common/h/dyn_regs.h, common/src/dyn_regs.C, dwarf/src/dwarfHandle.C, elf/h/Elf_X.h, elf/src/Elf_X.C, parseAPI/src/SymbolicExpression.C, proccontrol/src/process.C
This passed the test suite on x86_64.
=> Add basic support for EM_CUDA binary type

common/src/arch-power.C, common/src/arch-power.h, dyninstAPI/src/BPatch_loopTreeNode.C, dyninstAPI/src/BPatch_point.C, dyninstAPI/src/Relocation/CFG/RelocBlock.C, dyninstAPI/src/Relocation/CFG/RelocBlock.h, dyninstAPI/src/Relocation/CFG/RelocGraph.C, dyninstAPI/src/Relocation/CFG/RelocGraph.h, dyninstAPI/src/Relocation/CodeMover.C, dyninstAPI/src/Relocation/Springboard.C, dyninstAPI/src/Relocation/Transformers/Instrumenter.C, dyninstAPI/src/addressSpace.C, dyninstAPI/src/block.C, dyninstAPI/src/block.h, dyninstAPI/src/codegen-power.C, dyninstAPI/src/codegen-power.h, dyninstAPI/src/emit-power.h, dyninstAPI/src/function.C, dyninstAPI/src/function.h, dyninstAPI/src/image.C, dyninstAPI/src/inst-power.C, dyninstAPI/src/inst-power.h, dyninstAPI/src/mapped_object.C, dyninstAPI/src/parse-cfg.C, dyninstAPI/src/parse-cfg.h, dyninstAPI/src/unix.C, parseAPI/src/CodeObject.C, parseAPI/src/SymtabCodeSource.C
Fix dynamic instrumentation and binary rewriting on power 8 platforms
=> Power8 instrumentation fix

CMakeLists.txt
Install  the pdf doc files into the correct target doc directories.
=> Install docs into target doc dirs

dyninstAPI/src/addressSpace.C, dyninstAPI/src/image.C, dyninstAPI/src/inst-power.C, dyninstAPI/src/inst-power.h, dyninstAPI/src/mapped_object.C, dyninstAPI/src/mapped_object.h, dyninstAPI/src/parse-cfg.h, proccontrol/src/loadLibrary/codegen-ppc.C, symtabAPI/src/emitElf.C, symtabAPI/src/emitElfStatic.C
This PR fixes function replacement in rewriter mode and issue #502
=> Power abi v2 fixes

dwarf/src/dwarfFrameParser.C, dyninstAPI/src/parse-power.C, dyninstAPI_RT/src/RTcommon.c, dyninstAPI_RT/src/RTstatic_ctors_dtors-ppc64.c, proccontrol/src/process.C, symtabAPI/src/Object-elf.C, symtabAPI/src/emitElf.C, symtabAPI/src/emitElfStatic-ppc64.C, symtabAPI/src/emitElfStatic-x86.C, symtabAPI/src/emitElfStatic.C
Fixes most test suite failures on ppc running rhel8/fedora 28
=> Ppcle rhel8 fix

dyninstAPI/src/Relocation/Springboard.C, parseAPI/src/IndirectAnalyzer.C, parseAPI/src/Parser.C
This PR should fix the test suite hang observed on power 8.
I have run the hanging tests 1000 times without hanging.
@hainest Please create a dev branch for this PR, and it is ready to test on all platforms.
=> A few fixes for parallel parsing

patchAPI/example/README.md, patchAPI/example/main.cpp, patchAPI/example/mutatee/main.c
Using dyninstAPI to create the PatchMgr and PatchObject.  
I should point out that I have not succeeded in getting a pacthAPI example working that
uses only the patchAPI.
=> simple working hybrid example of patchAPI 

proccontrol/h/Event.h, proccontrol/h/PCProcess.h, proccontrol/h/ProcessSet.h, proccontrol/src/irpc.h, proccontrol/src/response.h, proccontrol/src/windows_handler.h
Tested with boost 1.70 and boost 1.61
=> Compilation fix for boost 1.70

cmake/Modules/FindTBB.cmake, cmake/ThreadingBuildingBlocks.cmake
A few fixes to make the new TBB CMake files compatible with the Spack build.
=> TBB spack fixes

symtabAPI/src/emitElf.C
when .got and .plt offsets are modified for ARMv8.
=> Updates TLS descriptors values in .dynamic section

dyninstAPI/src/dynProcess.C
This PR should fix #634 .
@stanfordcox Can you test whether this PR fixes the problem on your end?
=> Fix detach for trap springboards

CMakeLists.txt, cmake/Boost.cmake, cmake/ElfUtils.cmake, cmake/LibIberty.cmake, cmake/LibXml2.cmake, cmake/ThreadingBuildingBlocks.cmake
=> Use CMAKE_xx_COMPILER when building external dependencies

parseAPI/h/CFG.h
=> Delete duplicate friend declaration of Parser in Block

CMakeLists.txt
=> Deprecate Blue Gene/Q support

dyninstAPI/h/BPatch_process.h, dyninstAPI/src/BPatch_process.C, dyninstAPI/src/dynProcess.C, dyninstAPI/src/dynProcess.h
Add interface for checking whether thread level control is supported at the BPatch level.
=> Implement the check of ThreadDB at BPatch level

dataflowAPI/src/liveness.C, dyninstAPI/src/dynProcess.C, dyninstAPI/src/dynProcess.h, dyninstAPI/src/emit-aarch64.C, dyninstAPI/src/pcEventHandler.C, dyninstAPI/src/pcEventHandler.h, dyninstAPI_RT/h/dyninstAPI_RT.h, dyninstAPI_RT/src/RTcommon.c, dyninstAPI_RT/src/RTcommon.h, dyninstAPI_RT/src/RTlinux.c, dyninstAPI_RT/src/RTthread-aarch64.c, proccontrol/src/linux.C, stackwalk/src/linuxbsd-swk.C
The commit that I just pushed resolved lots of the crashes on libc-2.29 on aarch64.
Fixes #652
=> Fix instrumentation regressions for libc-2.29 on ARM

dataflowAPI/src/AbslocInterface.C, parseAPI/src/SymbolicExpression.C
=> Fixes for AbsRegion and jump table index slicing involving global variable

symtabAPI/src/dwarfWalker.C
How this is handled is implementation-defined.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64867
=> Do not use non-trivial types in varargs

dyninstAPI/src/parse-aarch64.C, dyninstAPI/src/parse-power.C, dyninstAPI/src/parse-x86.C
and warn user if it's not found.
=> Add search of libgcc.a to x86 and aarch64

parseAPI/src/Parser.C, symtabAPI/src/emitElf.C
@hainest This PR includes fixes that are helpful to get us being able to relocate libraries. It may not necessarily fix #753. But this PR includes necessary changes for me to be able to instrument libraries on one platform.
=> Potential fixes needed for relocating libraries

dataflowAPI/rose/x86_64InstructionSemantics.h, parseAPI/h/CFG.h, parseAPI/src/Block.C, parseAPI/src/Parser.C, parseAPI/src/Parser.h, parseAPI/src/ParserDetails.C, parseAPI/src/SymtabCodeSource.C
This PR includes necessary fixes for analyzing libxul.so from FireFox. 
Fix #747
=> Libxul fixes

common/src/linuxKludges.C, dyninstAPI/src/parse-cfg.h, dyninstAPI/src/unix.C, parseAPI/h/CFG.h, parseAPI/h/CFGFactory.h, parseAPI/src/Block.C, parseAPI/src/BoundFactData.C, parseAPI/src/CFGFactory.C, parseAPI/src/CFGModifier.C, parseAPI/src/IndirectAnalyzer.C, symtabAPI/h/Type.h, symtabAPI/src/Type-mem.h, symtabAPI/src/Type.C
This PR addresses a subset of the memory leaks identified in #756 .
With this PR, @stanfordcox can finish instrumentation test.
=> Memory leak fixes

elf/h/Elf_X.h, elf/src/Elf_X.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h
=> Elf ex numbering

symtabAPI/src/emitElf.h, symtabAPI/src/emitElfStatic.C
This was originally part of https://github.com/dyninst/dyninst/pull/317
=> Cleanup memory handling when emitting Elf for static libraries

dyninstAPI/src/BPatch.C, dyninstAPI/src/addressSpace.C, dyninstAPI/src/dynProcess.h, dyninstAPI/src/function.h, dyninstAPI/src/hybridCallbacks.C, dyninstAPI/src/mapped_object.C, dyninstAPI/src/pcEventHandler.C
This was originally part of https://github.com/dyninst/dyninst/pull/317
=> Clean up some includes

dyninstAPI/h/BPatch_addressSpace.h, dyninstAPI/h/BPatch_binaryEdit.h, dyninstAPI/h/BPatch_point.h, dyninstAPI/h/BPatch_process.h, dyninstAPI/src/BPatch_binaryEdit.C, dyninstAPI/src/BPatch_templates.C, dyninstAPI/src/dynProcess.C, dyninstAPI/src/instP.h, dyninstAPI/src/syscall-vxworks.C
It was removed by 0bc3980d1 in 2011.
Fixes #782
=> Remove usage of miniTramp class

dataflowAPI/src/SymEval.C
This was originally part of https://github.com/dyninst/dyninst/pull/317
=> Fix memory leak in SymEval::expandInsn

common/h/concurrent.h, common/h/dyntypes.h, dyninstAPI/src/codegen.C, dyninstAPI_RT/src/RTthread-power-asm.s, dyninstAPI_RT/src/RTthread-powerpc-asm.S
Fixes #497 
This is a public branch version of #631.
=> Make Dyninst buildable with Clang

dyninstAPI/h/BPatch_snippet.h, dyninstAPI/src/BPatch_snippet.C
This was deprecated by 4d15de8 in 2008.
Closes #819
=> Remove deprecated BPatch_regExpr

parseAPI/h/CFG.h, parseAPI/src/SymtabCodeSource.C
A rebased replacement PR for #412
=> Some necessary changes for overlapping text regions

dyninstAPI/src/image.h
This was originally part of #317.
=> Remove unused lineDict class

dyninstAPI/src/binaryEdit.h
This bug was introduced by #876. Although no tests failed there...
=> Ensure data is copied in memoryTracker::realloc

symtabAPI/src/emitElf.C, symtabAPI/src/emitElf.h
This was originally part of #317
=> Fix memory leaks in emitElf

parseAPI/src/Parser.C, symtabAPI/src/Object-elf.C, symtabAPI/src/Object.C, symtabAPI/src/Symtab-edit.C, symtabAPI/src/Symtab.C
Fixes 15 asserts that had side effects.  I believe the remainder are side effect free.
Fixes #926
=> Make assert expressions side effect free

parseAPI/src/IA_aarch64.C
This was introduced by 38370b0ee48 in 2016
=> Fix -Wreturn-type warning

parseAPI/src/BoundFactCalculator.C, parseAPI/src/BoundFactCalculator.h
This was removed by f87d17a in 2017
=> Remove BoundsFactCalculator::ThunkBound

parseAPI/src/BoundFactCalculator.C, parseAPI/src/BoundFactData.C, parseAPI/src/BoundFactData.h
This was remove by f87d17ac036c1 in 2017
=> Remove BoundFactCalculator::CheckZeroExtend

parseAPI/src/JumpTableIndexPred.C, parseAPI/src/JumpTableIndexPred.h
This was partially removed by f87d17ac036 in 2017
=> Remove JumpTableIndexPred::FillInOutEdges

parseAPI/src/ParseData.C, parseAPI/src/ParseData.h
This was removed by d327c37f216d in 2020
=> Remove empty region_data constructor

common/src/dyn_regs.C, parseAPI/src/SymbolicExpression.C, proccontrol/src/process.C
=> Fix unhandled enum values for Intel GPUs

COPYRIGHT, parseAPI/h/SymLiteCodeSource.h, parseAPI/src/CodeSource.C, parseAPI/src/SymLiteCodeSource.C
NB: Only the copyrights explicitly belonging to Dyninst were updated
closes #830
=> Update copyrights to 2021

dataflowAPI/src/slicing.C, instructionAPI/src/InstructionDecoder-power.C, parseAPI/src/Function.C, parseAPI/src/Parser.C
Fix all reported segfault and abort mentioned #1035
=> Fix data races and asserts discovered on Power 

common/src/debug_common.C, common/src/debug_common.h, symtabAPI/src/dwarfWalker.C
=> Fixing calling `dwarf_getabbrevcode` and refactoring debug logging in common

common/h/entryIDs.h, common/src/arch-x86.C
@tylergu Could you try this out and see if you can now parse this instruction?
=> Add xsave instruction

common/h/entryIDs.h, common/src/arch-x86.C
@tylergu So sorry this took so long! Could you test this in SPI?
=> Add x86_64 xrstor instruction

common/h/entryIDs.h, common/src/arch-x86.C
@tylergu Does this solve your final parsing issue?
=> Add x86 xsavec instruction

parseThat/src/sha1.C
The code should have been a string literal not a char literal.
Fixes #1089
=> fix broken cast of a char literal to pointer

cmake/LanguageStandards.cmake
=> use the C11 standard for C code in Dyninst

cmake/optimization.cmake
=> update optimization (-Og) and debug flags (-g3)

dyninstAPI/src/addressSpace.C, dyninstAPI/src/addressSpace.h
This was removed by 47c4dfe96 in 2010.
=> Remove AddressSpace::causeTemplateInstantiations

symtabAPI/src/Type-mem.h
=> Removed incorrect/unnecessary/error-prone use of realloc

.github/workflows/base-containers.yaml
we do not need the build on PR, but we do need on merge into MASTER not MAIN
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> fixing workflow trigger

.github/workflows/test-dyninst.yaml, docker/Dockerfile.test, docker/README.md, docker/test.sh
The package build was successful, so here is the promised next step - a workflow that will use the automated build to run tests on the new code.
I likely am going to sleep after this and will pick up in the morning
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> start of work to add automated testing to dyninst!

symtabAPI/doc/API/Symtab/Module.tex
=> Symtab::module documentation cleanup

symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Symtab.C
Fix #1191 and remove some related dead code.
=> Fix handling of CUBINs generated by CUDA-11.6

common/src/dyn_regs.C, instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.C, instructionAPI/src/AMDGPU/cdna2/decodeOperands.C, instructionAPI/src/Register.C
@mxz297 @bbiiggppiigg
We should try to find a better way of doing code reviews. I missed all of this when looking over the PR. It would be great if we could do them iteratively with smaller amounts of code changes. Understandably, this can be hard to do for active development of new features.
=> Fix compiler warnings in amdgpu cdna2 code

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
Fix to only process the DWARF for a function (subprogram) once if it is defined
in multiple compilation units within a library or executable.  This prevents
duplication of parameters, local variables and use of thread-unsafe data
structures from concurrent threads.
Fixes #1214
=> Correctly handle DWARF subroutines during parallel parsing

.github/workflows/base-containers.yaml
This should have been part of #1211
=> Docker: update dependency versions in base container config

.github/workflows/libabigail.yaml
I am not sure if the artifact is extracted relative or not, so will need to update the workflow to account for that. This is also a new strategy that will try to do the new build/retrieval of artifacts from previous containers - have not tried this yet!
- This will close https://github.com/dyninst/dyninst/issues/1218
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
=> Docker: testing workflow to run libabigail

docker/Dockerfile.test, docker/build.sh
- remove old code before copying code into testing container
- build with verbosity in build.sh (this helps when build errors occur)
- Closes #1272
=> Tweak build.sh + Dockerfile.test

parseAPI/src/SymtabCodeSource.C
Always include an an executable's entry point as a parsing hint,
otherwise for stripped binaries no functions are parsed.
=> Add exec entry point to parse hints is missing

dwarf/src/dwarfFrameParser.C, parseAPI/src/GraphAdapter.C, proccontrol/h/PCProcess.h
See commit messages for rationales.
=> Remove outdated Boost version checks

docker/Dockerfile
https://spack.readthedocs.io/en/v0.19.1/environments.html#spec-concretization
fixes #1365
=> update spack.yaml for spack v0.19.1

instructionAPI/src/Instruction.C
Also fixes  this issue for gfx908 (mi25 and mi200 already fixed)
=> Fix all-through instructions for newly added AMD gpu gfx908

instructionAPI/src/AMDGPU/cdna2/InstructionDecoder-amdgpu-cdna2.C, instructionAPI/src/AMDGPU/gfx908/InstructionDecoder-amdgpu-gfx908.C, instructionAPI/src/AMDGPU/vega/InstructionDecoder-amdgpu-vega.C
These were showing up on ufront@rice.
=> Add missing <array> includes

dyninstAPI/src/BPatch.C, symtabAPI/h/Type.h, symtabAPI/src/Type.C, symtabAPI/src/dwarfWalker.C
This should be rebase merged - **not** squashed!
=> ABI-breaking changes for updated DWARF enum and C++ r-value reference types

.github/workflows/spack-build.yaml
Do a weekly build of Dyninst from the latest spack.
=> CI workflow to build from spack

docker/Dockerfile, docker/Dockerfile.ubuntu, docker/build_elfutils.sh
Should be merged before #1419.
=> Refactor Dockerfile.ubuntu

.github/workflows/build.yaml, .github/workflows/compiler-multibuild.yaml
@kupsch This will build the Euclidean product of compiler,version,build_type for gcc-7:12 and clang-7:15. How does this compare with what you are doing?
=> CI compiler multibuilds

common/src/addrtranslate-win.C, dyninstAPI/src/pdwinnt.C, dyninstAPI/src/pdwinntDL.C, dyninstAPI_RT/src/RTwinnt.c, proccontrol/src/DecoderWindows.C, proccontrol/src/windows_process.C, symtabAPI/src/Object-nt.C, symtabAPI/src/emitWin.h
These were all found with cppcheck.
=> Fix windows warnings

dyninstAPI/src/BPatch_addressSpace.C, dyninstAPI/src/codegen-power.C, instructionAPI/src/InstructionDecoder-aarch64.C, parseAPI/src/Block.C, parseAPI/src/Function.C, patchAPI/h/Point.h, proccontrol/src/x86_process.C
These were found using cppcheck.
=> Fix undefined behavior in integer operations

symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object-nt.C, symtabAPI/src/Object.C, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C
Please check this carefully. I _think_ I've correctly deduced that it was only ever written to.
=> Remove AObject::symsToModules_

dwarf/h/dwarf_cu_info.hpp, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
This centralizes the process and gives readable names to what's happening.
=> Refactor extracting CU tags from DWARF

dwarf/h/dwarf_cu_info.h, symtabAPI/src/Object-elf.C, symtabAPI/src/dwarfWalker.C
Refactor the type detection functions for DIEs to make them clearer in their meaning.
=> Refactor dwarf/dwarf_names.h

.github/workflows/consumers.yaml
'MUST' detects MPI usage errors. Comes from RWTH Aachen University.
=> Github CI: Add weekly build of MUST

.github/workflows/consumers.yaml
I forgot to do this before merging #1527.
=> GithubCI: Re-enable consumer builds

symtabAPI/src/dwarfWalker.C, symtabAPI/src/dwarfWalker.h
Its usage was removed by 1aec77b59 in 2017.
=> Remove dwarfWalker::deallocateLocationList

symtabAPI/src/Symtab.C
A function should only be added to everyFunction if it was not already in funcsByOffset or if it lives in a different code region from the function found with the same offset.
This was introduced by https://github.com/dyninst/dyninst/pull/1534.
=> Fix duplicate symbol entries in Symtab:everyFunction

.github/workflows/pr-tests.yaml, docker/build.sh
These were causing false negatives in testing.
=> GithubCI: improve error handling

symtabAPI/src/Module.C
This was introduced by 5835e29f.
=> Fix redundant parsing of linemap information

dyninstAPI/src/ast.C, dyninstAPI/src/ast.h
This is now a class invariant. Found by cppcheck's nullPointerRedundantCheck.
=> Guarantee operands in AstOperatorNode are non-null

dyninstAPI/src/binaryEdit.C
They were commented out by 918945edb in 2011.
=> Remove addTrapTableSpace_win and addTrapTable_win in binaryEdit.C

instructionAPI/h/Expression.h, instructionAPI/h/Operation_impl.h, instructionAPI/src/Operation.C
I ultimately decided not to rename the file, even though it really should be.
=> Clean up InstructionAPI::Operation

docker/Dockerfile.ubuntu, docker/build_elfutils.sh
This also correctly passed the number of build jobs to build_elfutils.sh.
=> Docker: Use named arguments in build scripts

.github/workflows/dev-containers.yaml, .github/workflows/pr-tests.yaml, docker/build_base_images.sh
The base images for these have been manually created and uploaded.
=> GithubCI : Add more Ubuntu and Fedora versions

.github/workflows/consumers.yaml
@kupsch This should be the final item to get all weekly CI builds at 100% passing.
=> GithubCI: update systemtap weekly test build

instructionAPI/src/InstructionCategories.C, parseAPI/src/IA_aarch64.C, parseAPI/src/IA_power.C, parseAPI/src/IA_x86.C
=> Improve syscall and interrupt instruction detection

COPYRIGHT, parseAPI/h/SymLiteCodeSource.h, parseAPI/src/CodeSource.C, parseAPI/src/SymLiteCodeSource.C
- update COPYRIGHT files's notice to include 2024
- update copyright header in source files to reference COPYRIGHT
=> update copyright header and date

dataflowAPI/src/liveness.C, dyninstAPI/src/Relocation/Transformers/Movement-analysis.C, dyninstAPI/src/Relocation/Transformers/Movement-analysis.h, instructionAPI/CMakeLists.txt, instructionAPI/h/syscalls.h, instructionAPI/src/syscalls.C, parseAPI/src/IA_IAPI.C, parseAPI/src/IA_IAPI.h, parseAPI/src/IA_aarch64.C, parseAPI/src/IA_aarch64.h, parseAPI/src/IA_amdgpu.C, parseAPI/src/IA_amdgpu.h, parseAPI/src/IA_power.C, parseAPI/src/IA_power.h, parseAPI/src/IA_x86.C, parseAPI/src/IA_x86.h, parseAPI/src/Parser.C
I'll refactor the interrupt detection in a separate PR.
=> Unify system call detection

cmake/DyninstPlatform.cmake
Adds better detection of 32-bit x86 platforms and separates out the 64-bit ones.
Should fix #1726, but will need confirmation.
=> CMake: update x86 platform detection

common/CMakeLists.txt, common/src/dyn_regs.C, common/src/registers/MachRegister.C, common/src/registers/MachRegisterCache.h
=> MachRegister: fix initialization order bug

dyninstAPI/src/BPatch_process.C, dyninstAPI/src/freebsd.C, dyninstAPI/src/linux-x86.C, dyninstAPI/src/mapped_object.C, parseAPI/src/LoopAnalyzer.C
This function doesn't need to exist since there is a standard way of doing it now.
=> Replace utos with std::to_string

common/src/arch-x86.C
`0x8f` can be either the first byte of XOP prefix, or the opcode of POP instruction. The disambiguation is resolved by `map_select` field of XOP's second byte. If it is XOP prefix, than the field should be from [0x8, 0x1f] range. Otherwise it is ModRM byte, and `0x8f` is an opcode. The only instruction with this opcode is POP, and it requires `Reg` filed of ModRM to be 0.
`map_select` field is bits [4:0], `reg` field is [5:3]. Basically, if bits [4:3] are 0, then this is not a XOP prefix.
The group that POP belongs to is called "Group 1a" by AMD documentation, but this name is already used for "Group 1 opcode 80h", thus I called it "Group 1A".
Code sample to test:
```
_start:
pop (%rax)
```
=> x86: Handle disambiguation between XOP prefix and POP instruction

common/src/registers/MachRegister.C
#1824 is needed before this can be merged.
=> Implement MachRegister::getBaseRegister for aarch64

common/h/registers/MachRegister.h, common/src/arch-power.h, dataflowAPI/h/ABI.h, instructionAPI/src/ArchSpecificFormatters.C
This is effectively a cleanup from IWYU.
=> Fix transitive includes from MachRegister.h

dataflowAPI/rose/registers/convert.C, dataflowAPI/rose/registers/x86.h
=> Fix x86 MachRegister -> ROSE register conversion

dataflowAPI/rose/registers/aarch64.h, dataflowAPI/rose/registers/convert.C
=> Fix aarch64 MachRegister -> ROSE register conversion

common/src/registers/MachRegister.C
Needed for https://github.com/dyninst/unit-tests/pull/11.
=> Handle all architectures in getSyscallNumberOReg

dataflowAPI/src/AbslocInterface.C
Preserve full register in AbsRegionConverter::convert(RegisterAST::Ptr)
ROSE distinguishes partial registers from full ones, so that needs to be
reflected here since this class is the main point of conversion between
Dyninst and ROSE.
Example from aarch64:
0x94C: ldr W0, [X1, W0, lsl 0x2]
The created Assignment is
@94c<[aarch64::x0]>[aarch64::x1]>[aarch64::x0]>H[]
Note that the assignment thinks the first register is x0, rather than
w0. Passing this through AssignmentConverter::convert, the generated
ROSE expressions are
SgAsmIntegerType:SgAsmDirectRegisterExpression for 0x94C W0
SgAsmIntegerType:SgAsmDirectRegisterExpression for 0x94C X1
SgAsmIntegerType:SgAsmDirectRegisterExpression for 0x94C W0
Now, the first operand is correct. However, this operand is not
recognized in …
=> Preserve full register in AbsRegionConverter::convert(RegisterAST::Ptr)

.github/actions/build-fedora/action.yaml, .github/actions/build-ubuntu/action.yaml, .github/actions/build/action.yaml, docker/build.sh
=> GithubCI: update build scripts

common/h/mnemonics/AMDGPU/gfx908_entryIDs.h, common/h/mnemonics/AMDGPU/gfx90a_entryIDs.h, common/h/mnemonics/AMDGPU/gfx940_entryIDs.h, common/h/mnemonics/IntelGPU/generic_entryIDs.h, common/h/mnemonics/NVIDIA/generic_entryIDs.h, instructionAPI/src/Instruction.C
Fixes #1869
@bbiiggppiigg Does the work with your importer?
@mwkrentel Could you try this with HPCToolkit?
=> Add missing invalid mnemonics

dwarf/src/dwarfHandle.C, elf/src/Elf_X.C
=> Add AMDGPU GFX941 and GFX942 as GFX940 arch

cmake/Modules/DyninstLinkProperties.cmake, symtabAPI/doc/API/Symtab/Symtab.tex, symtabAPI/h/Symtab.h, symtabAPI/src/Object-elf.C, symtabAPI/src/Object-elf.h, symtabAPI/src/Object.h, symtabAPI/src/Symtab.C, tests/regression/CMakeLists.txt, tests/regression/symtabAPI/CMakeLists.txt, tests/regression/symtabAPI/Symtab/CMakeLists.txt, tests/regression/symtabAPI/Symtab/file_properties/CMakeLists.txt, tests/regression/symtabAPI/Symtab/file_properties/isExec.cpp, tests/regression/symtabAPI/Symtab/file_properties/isExecutable.cpp, tests/regression/symtabAPI/Symtab/file_properties/isPositionIndependent.cpp, tests/regression/symtabAPI/Symtab/file_properties/isSharedLibrary.cpp, tests/regression/symtabAPI/Symtab/file_properties/isStaticBinary.cpp, tests/regression/symtabAPI/Symtab/file_properties/isStripped.cpp, tests/regression/symtabAPI/Symtab/file_properties/test.cpp
The current file-property checks aren't sufficient to detect all
cases- PIE, in particular.
=> Add Symtab::isPositionIndependent

common/src/util.C, symlite/src/SymLite-elf.C
That's the only place it's used.
=> Move getSymelfCache into SymLite-elf.C

symtabAPI/h/Symtab.h, symtabAPI/src/Symtab.C, symtabAPI/src/symtab_impl.hpp
This was causing build errors for unit tests.
=> Move Symtab::mf member into symtab_impl

instructionAPI/src/Instruction.C, instructionAPI/src/InstructionDecoder-power.C, parseAPI/src/IA_power.C
This should have been part of 64499aa304.
Fixes #1072
=> Fix PowerPC branch instruction semantics

dyninstAPI/src/parse-cfg.C, dyninstAPI/src/parse-cfg.h
Its usage was removed by 6c65e3c9a8 in 2007.
=> Remove parse_func::changeModule

instructionAPI/h/Expression.h, instructionAPI/src/Expression.C, instructionAPI/src/InstructionAST.C
Its usage was removed by 3714412b11cba in 2017.
=> Remove DummyExpr

instructionAPI/h/BinaryFunction.h, instructionAPI/h/Dereference.h, instructionAPI/h/Immediate.h, instructionAPI/h/MultiRegister.h, instructionAPI/h/Register.h
These will be needed for an upcoming PR.
Requires #1957.
=> Make overrides explicit in AST classes

cmake/DyninstPlatform.cmake
=> [CMake][AMDGPU] Fix typo for gfx908
